//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.25 at 10:39:55 PM BST 
//


package org.mitre.maec.xmlschema.maec_core_1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * ActionCollectionType is intended to provide a method for characterizing collections of actions. This can be useful for organizing actions that may be related and where the exact relationship is unknown, as well as actions whose associated behavior has not yet been established.
 * 
 * <p>Java class for ActionCollectionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ActionCollectionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Affinity_Type" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Affinity_Degree" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Description" type="{http://maec.mitre.org/XMLSchema/maec-core-1}StructuredTextType" minOccurs="0"/>
 *         &lt;choice maxOccurs="unbounded">
 *           &lt;element name="Action_Sub-Collection" type="{http://maec.mitre.org/XMLSchema/maec-core-1}ActionCollectionType" minOccurs="0"/>
 *           &lt;element name="Action" type="{http://maec.mitre.org/XMLSchema/maec-core-1}ActionType" minOccurs="0"/>
 *           &lt;element name="Action_Reference" type="{http://maec.mitre.org/XMLSchema/maec-core-1}ActionReferenceType" minOccurs="0"/>
 *         &lt;/choice>
 *         &lt;element name="Effects" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Effect" type="{http://maec.mitre.org/XMLSchema/maec-core-1}EffectType" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="Effect_Reference" type="{http://maec.mitre.org/XMLSchema/maec-core-1}EffectReferenceType" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://maec.mitre.org/XMLSchema/maec-core-1}ActionCollIDPattern" />
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ActionCollectionType", propOrder = {
    "affinityType",
    "affinityDegree",
    "description",
    "actionSubCollectionOrActionOrActionReference",
    "effects"
})
public class ActionCollectionType {

    @XmlElement(name = "Affinity_Type")
    protected String affinityType;
    @XmlElement(name = "Affinity_Degree")
    protected String affinityDegree;
    @XmlElement(name = "Description")
    protected StructuredTextType description;
    @XmlElements({
        @XmlElement(name = "Action_Sub-Collection", type = ActionCollectionType.class),
        @XmlElement(name = "Action", type = ActionType.class),
        @XmlElement(name = "Action_Reference", type = ActionReferenceType.class)
    })
    protected List<Object> actionSubCollectionOrActionOrActionReference;
    @XmlElement(name = "Effects")
    protected ActionCollectionType.Effects effects;
    @XmlAttribute(name = "id", required = true)
    protected String id;
    @XmlAttribute(name = "name")
    protected String name;

    /**
     * Gets the value of the affinityType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAffinityType() {
        return affinityType;
    }

    /**
     * Sets the value of the affinityType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAffinityType(String value) {
        this.affinityType = value;
    }

    /**
     * Gets the value of the affinityDegree property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAffinityDegree() {
        return affinityDegree;
    }

    /**
     * Sets the value of the affinityDegree property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAffinityDegree(String value) {
        this.affinityDegree = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link StructuredTextType }
     *     
     */
    public StructuredTextType getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link StructuredTextType }
     *     
     */
    public void setDescription(StructuredTextType value) {
        this.description = value;
    }

    /**
     * Gets the value of the actionSubCollectionOrActionOrActionReference property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the actionSubCollectionOrActionOrActionReference property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getActionSubCollectionOrActionOrActionReference().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ActionCollectionType }
     * {@link ActionType }
     * {@link ActionReferenceType }
     * 
     * 
     */
    public List<Object> getActionSubCollectionOrActionOrActionReference() {
        if (actionSubCollectionOrActionOrActionReference == null) {
            actionSubCollectionOrActionOrActionReference = new ArrayList<Object>();
        }
        return this.actionSubCollectionOrActionOrActionReference;
    }

    /**
     * Gets the value of the effects property.
     * 
     * @return
     *     possible object is
     *     {@link ActionCollectionType.Effects }
     *     
     */
    public ActionCollectionType.Effects getEffects() {
        return effects;
    }

    /**
     * Sets the value of the effects property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActionCollectionType.Effects }
     *     
     */
    public void setEffects(ActionCollectionType.Effects value) {
        this.effects = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Effect" type="{http://maec.mitre.org/XMLSchema/maec-core-1}EffectType" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="Effect_Reference" type="{http://maec.mitre.org/XMLSchema/maec-core-1}EffectReferenceType" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "effect",
        "effectReference"
    })
    public static class Effects {

        @XmlElement(name = "Effect")
        protected List<EffectType> effect;
        @XmlElement(name = "Effect_Reference")
        protected List<EffectReferenceType> effectReference;

        /**
         * Gets the value of the effect property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the effect property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getEffect().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link EffectType }
         * 
         * 
         */
        public List<EffectType> getEffect() {
            if (effect == null) {
                effect = new ArrayList<EffectType>();
            }
            return this.effect;
        }

        /**
         * Gets the value of the effectReference property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the effectReference property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getEffectReference().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link EffectReferenceType }
         * 
         * 
         */
        public List<EffectReferenceType> getEffectReference() {
            if (effectReference == null) {
                effectReference = new ArrayList<EffectReferenceType>();
            }
            return this.effectReference;
        }

    }

}
