//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.25 at 10:39:55 PM BST 
//


package org.mitre.maec.xmlschema.maec_core_1;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * ActionType is intended to serve as a method for the characterization of actions found or observed in malware. Actions can be thought of as system state changes and similar operations that represent the fundamental low-level operation of malware. Some examples include the creation of a file, deletion of a registry key, and the sending of some arbitrary packets on a socket.
 * 
 * <p>Java class for ActionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ActionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Description" type="{http://maec.mitre.org/XMLSchema/maec-core-1}StructuredTextType" minOccurs="0"/>
 *         &lt;element name="Discovery_Method" type="{http://maec.mitre.org/XMLSchema/maec-core-1}DiscoveryMethod" minOccurs="0"/>
 *         &lt;element name="Action_Initiator" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Initiator_Object" type="{http://maec.mitre.org/XMLSchema/maec-core-1}ObjectReferenceType" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="type">
 *                   &lt;simpleType>
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                       &lt;enumeration value="Process"/>
 *                       &lt;enumeration value="Other"/>
 *                     &lt;/restriction>
 *                   &lt;/simpleType>
 *                 &lt;/attribute>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Action_Implementation" type="{http://maec.mitre.org/XMLSchema/maec-core-1}ActionImplementationType" minOccurs="0"/>
 *         &lt;element name="Objects" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Object_Reference" type="{http://maec.mitre.org/XMLSchema/maec-core-1}ObjectReferenceType" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="Object" type="{http://maec.mitre.org/XMLSchema/maec-core-1}ObjectType" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Effects" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Effect" type="{http://maec.mitre.org/XMLSchema/maec-core-1}EffectType" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="Effect_Reference" type="{http://maec.mitre.org/XMLSchema/maec-core-1}EffectReferenceType" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Related_Actions" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Related_Action" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Action_Reference" type="{http://maec.mitre.org/XMLSchema/maec-core-1}ActionReferenceType"/>
 *                             &lt;element name="Nature_of_Relationship">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;enumeration value="Following_Dependency"/>
 *                                   &lt;enumeration value="Preceding_Dependency"/>
 *                                   &lt;enumeration value="Coexistence_Dependency"/>
 *                                   &lt;enumeration value="Operate_On_Same_Object"/>
 *                                   &lt;enumeration value="Other"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://maec.mitre.org/XMLSchema/maec-core-1}ActionIDPattern" />
 *       &lt;attribute name="type" type="{http://maec.mitre.org/XMLSchema/maec-core-1}ActionTypeEnum" />
 *       &lt;attribute name="action_name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ordinal_position" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
 *       &lt;attribute name="successful" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="timestamp" type="{http://www.w3.org/2001/XMLSchema}time" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ActionType", propOrder = {
    "description",
    "discoveryMethod",
    "actionInitiator",
    "actionImplementation",
    "objects",
    "effects",
    "relatedActions"
})
public class ActionType {

    @XmlElement(name = "Description")
    protected StructuredTextType description;
    @XmlElement(name = "Discovery_Method")
    protected DiscoveryMethod discoveryMethod;
    @XmlElement(name = "Action_Initiator")
    protected ActionType.ActionInitiator actionInitiator;
    @XmlElement(name = "Action_Implementation")
    protected ActionImplementationType actionImplementation;
    @XmlElement(name = "Objects")
    protected ActionType.Objects objects;
    @XmlElement(name = "Effects")
    protected ActionType.Effects effects;
    @XmlElement(name = "Related_Actions")
    protected ActionType.RelatedActions relatedActions;
    @XmlAttribute(name = "id", required = true)
    protected String id;
    @XmlAttribute(name = "type")
    protected ActionTypeEnum type;
    @XmlAttribute(name = "action_name")
    protected String actionName;
    @XmlAttribute(name = "ordinal_position")
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger ordinalPosition;
    @XmlAttribute(name = "successful")
    protected Boolean successful;
    @XmlAttribute(name = "timestamp")
    @XmlSchemaType(name = "time")
    protected XMLGregorianCalendar timestamp;

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link StructuredTextType }
     *     
     */
    public StructuredTextType getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link StructuredTextType }
     *     
     */
    public void setDescription(StructuredTextType value) {
        this.description = value;
    }

    /**
     * Gets the value of the discoveryMethod property.
     * 
     * @return
     *     possible object is
     *     {@link DiscoveryMethod }
     *     
     */
    public DiscoveryMethod getDiscoveryMethod() {
        return discoveryMethod;
    }

    /**
     * Sets the value of the discoveryMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link DiscoveryMethod }
     *     
     */
    public void setDiscoveryMethod(DiscoveryMethod value) {
        this.discoveryMethod = value;
    }

    /**
     * Gets the value of the actionInitiator property.
     * 
     * @return
     *     possible object is
     *     {@link ActionType.ActionInitiator }
     *     
     */
    public ActionType.ActionInitiator getActionInitiator() {
        return actionInitiator;
    }

    /**
     * Sets the value of the actionInitiator property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActionType.ActionInitiator }
     *     
     */
    public void setActionInitiator(ActionType.ActionInitiator value) {
        this.actionInitiator = value;
    }

    /**
     * Gets the value of the actionImplementation property.
     * 
     * @return
     *     possible object is
     *     {@link ActionImplementationType }
     *     
     */
    public ActionImplementationType getActionImplementation() {
        return actionImplementation;
    }

    /**
     * Sets the value of the actionImplementation property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActionImplementationType }
     *     
     */
    public void setActionImplementation(ActionImplementationType value) {
        this.actionImplementation = value;
    }

    /**
     * Gets the value of the objects property.
     * 
     * @return
     *     possible object is
     *     {@link ActionType.Objects }
     *     
     */
    public ActionType.Objects getObjects() {
        return objects;
    }

    /**
     * Sets the value of the objects property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActionType.Objects }
     *     
     */
    public void setObjects(ActionType.Objects value) {
        this.objects = value;
    }

    /**
     * Gets the value of the effects property.
     * 
     * @return
     *     possible object is
     *     {@link ActionType.Effects }
     *     
     */
    public ActionType.Effects getEffects() {
        return effects;
    }

    /**
     * Sets the value of the effects property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActionType.Effects }
     *     
     */
    public void setEffects(ActionType.Effects value) {
        this.effects = value;
    }

    /**
     * Gets the value of the relatedActions property.
     * 
     * @return
     *     possible object is
     *     {@link ActionType.RelatedActions }
     *     
     */
    public ActionType.RelatedActions getRelatedActions() {
        return relatedActions;
    }

    /**
     * Sets the value of the relatedActions property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActionType.RelatedActions }
     *     
     */
    public void setRelatedActions(ActionType.RelatedActions value) {
        this.relatedActions = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link ActionTypeEnum }
     *     
     */
    public ActionTypeEnum getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActionTypeEnum }
     *     
     */
    public void setType(ActionTypeEnum value) {
        this.type = value;
    }

    /**
     * Gets the value of the actionName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActionName() {
        return actionName;
    }

    /**
     * Sets the value of the actionName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActionName(String value) {
        this.actionName = value;
    }

    /**
     * Gets the value of the ordinalPosition property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getOrdinalPosition() {
        return ordinalPosition;
    }

    /**
     * Sets the value of the ordinalPosition property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setOrdinalPosition(BigInteger value) {
        this.ordinalPosition = value;
    }

    /**
     * Gets the value of the successful property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSuccessful() {
        return successful;
    }

    /**
     * Sets the value of the successful property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSuccessful(Boolean value) {
        this.successful = value;
    }

    /**
     * Gets the value of the timestamp property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTimestamp() {
        return timestamp;
    }

    /**
     * Sets the value of the timestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTimestamp(XMLGregorianCalendar value) {
        this.timestamp = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Initiator_Object" type="{http://maec.mitre.org/XMLSchema/maec-core-1}ObjectReferenceType" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="type">
     *         &lt;simpleType>
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *             &lt;enumeration value="Process"/>
     *             &lt;enumeration value="Other"/>
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "initiatorObject"
    })
    public static class ActionInitiator {

        @XmlElement(name = "Initiator_Object")
        protected ObjectReferenceType initiatorObject;
        @XmlAttribute(name = "type")
        protected String type;

        /**
         * Gets the value of the initiatorObject property.
         * 
         * @return
         *     possible object is
         *     {@link ObjectReferenceType }
         *     
         */
        public ObjectReferenceType getInitiatorObject() {
            return initiatorObject;
        }

        /**
         * Sets the value of the initiatorObject property.
         * 
         * @param value
         *     allowed object is
         *     {@link ObjectReferenceType }
         *     
         */
        public void setInitiatorObject(ObjectReferenceType value) {
            this.initiatorObject = value;
        }

        /**
         * Gets the value of the type property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getType() {
            return type;
        }

        /**
         * Sets the value of the type property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setType(String value) {
            this.type = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Effect" type="{http://maec.mitre.org/XMLSchema/maec-core-1}EffectType" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="Effect_Reference" type="{http://maec.mitre.org/XMLSchema/maec-core-1}EffectReferenceType" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "effect",
        "effectReference"
    })
    public static class Effects {

        @XmlElement(name = "Effect")
        protected List<EffectType> effect;
        @XmlElement(name = "Effect_Reference")
        protected List<EffectReferenceType> effectReference;

        /**
         * Gets the value of the effect property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the effect property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getEffect().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link EffectType }
         * 
         * 
         */
        public List<EffectType> getEffect() {
            if (effect == null) {
                effect = new ArrayList<EffectType>();
            }
            return this.effect;
        }

        /**
         * Gets the value of the effectReference property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the effectReference property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getEffectReference().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link EffectReferenceType }
         * 
         * 
         */
        public List<EffectReferenceType> getEffectReference() {
            if (effectReference == null) {
                effectReference = new ArrayList<EffectReferenceType>();
            }
            return this.effectReference;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Object_Reference" type="{http://maec.mitre.org/XMLSchema/maec-core-1}ObjectReferenceType" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="Object" type="{http://maec.mitre.org/XMLSchema/maec-core-1}ObjectType" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "objectReference",
        "object"
    })
    public static class Objects {

        @XmlElement(name = "Object_Reference")
        protected List<ObjectReferenceType> objectReference;
        @XmlElement(name = "Object")
        protected List<ObjectType> object;

        /**
         * Gets the value of the objectReference property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the objectReference property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getObjectReference().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ObjectReferenceType }
         * 
         * 
         */
        public List<ObjectReferenceType> getObjectReference() {
            if (objectReference == null) {
                objectReference = new ArrayList<ObjectReferenceType>();
            }
            return this.objectReference;
        }

        /**
         * Gets the value of the object property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the object property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getObject().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ObjectType }
         * 
         * 
         */
        public List<ObjectType> getObject() {
            if (object == null) {
                object = new ArrayList<ObjectType>();
            }
            return this.object;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Related_Action" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Action_Reference" type="{http://maec.mitre.org/XMLSchema/maec-core-1}ActionReferenceType"/>
     *                   &lt;element name="Nature_of_Relationship">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;enumeration value="Following_Dependency"/>
     *                         &lt;enumeration value="Preceding_Dependency"/>
     *                         &lt;enumeration value="Coexistence_Dependency"/>
     *                         &lt;enumeration value="Operate_On_Same_Object"/>
     *                         &lt;enumeration value="Other"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "relatedAction"
    })
    public static class RelatedActions {

        @XmlElement(name = "Related_Action", required = true)
        protected List<ActionType.RelatedActions.RelatedAction> relatedAction;

        /**
         * Gets the value of the relatedAction property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the relatedAction property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getRelatedAction().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ActionType.RelatedActions.RelatedAction }
         * 
         * 
         */
        public List<ActionType.RelatedActions.RelatedAction> getRelatedAction() {
            if (relatedAction == null) {
                relatedAction = new ArrayList<ActionType.RelatedActions.RelatedAction>();
            }
            return this.relatedAction;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Action_Reference" type="{http://maec.mitre.org/XMLSchema/maec-core-1}ActionReferenceType"/>
         *         &lt;element name="Nature_of_Relationship">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;enumeration value="Following_Dependency"/>
         *               &lt;enumeration value="Preceding_Dependency"/>
         *               &lt;enumeration value="Coexistence_Dependency"/>
         *               &lt;enumeration value="Operate_On_Same_Object"/>
         *               &lt;enumeration value="Other"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "actionReference",
            "natureOfRelationship"
        })
        public static class RelatedAction {

            @XmlElement(name = "Action_Reference", required = true)
            protected ActionReferenceType actionReference;
            @XmlElement(name = "Nature_of_Relationship", required = true)
            protected String natureOfRelationship;

            /**
             * Gets the value of the actionReference property.
             * 
             * @return
             *     possible object is
             *     {@link ActionReferenceType }
             *     
             */
            public ActionReferenceType getActionReference() {
                return actionReference;
            }

            /**
             * Sets the value of the actionReference property.
             * 
             * @param value
             *     allowed object is
             *     {@link ActionReferenceType }
             *     
             */
            public void setActionReference(ActionReferenceType value) {
                this.actionReference = value;
            }

            /**
             * Gets the value of the natureOfRelationship property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNatureOfRelationship() {
                return natureOfRelationship;
            }

            /**
             * Sets the value of the natureOfRelationship property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNatureOfRelationship(String value) {
                this.natureOfRelationship = value;
            }

        }

    }

}
