//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.25 at 10:39:55 PM BST 
//


package org.mitre.maec.xmlschema.maec_core_1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.HexBinaryAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;
import xml.metadatasharing.UriObject;


/**
 * ActionImplementationType is intended to serve as a method for the characterization of action implementations. Currently supported are implementation achieved through API function calls and abstractly defined code.
 * 		
 * 
 * <p>Java class for ActionImplementationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ActionImplementationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element name="API_Call" type="{http://maec.mitre.org/XMLSchema/maec-core-1}APICallType" minOccurs="0"/>
 *           &lt;element name="Code" type="{http://maec.mitre.org/XMLSchema/maec-core-1}CodeType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;/choice>
 *         &lt;element name="Platform" type="{http://maec.mitre.org/XMLSchema/maec-core-1}CPESpecificationType" minOccurs="0"/>
 *         &lt;element name="Data_Read" type="{http://maec.mitre.org/XMLSchema/maec-core-1}DataType" minOccurs="0"/>
 *         &lt;element name="Data_Written" type="{http://maec.mitre.org/XMLSchema/maec-core-1}DataType" minOccurs="0"/>
 *         &lt;element name="File_System_Action_Attributes" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Existing_File_Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Destination_File_Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Access_Mode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Flags" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Open_Mode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="File_Attributes" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="IPC_Action_Attributes" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Initial_Owner" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Thread_ID" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *                   &lt;element name="Target_PID" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *                   &lt;element name="Start_Address" type="{http://www.w3.org/2001/XMLSchema}hexBinary" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Process_Action_Attributes" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Process_Base_Address" type="{http://www.w3.org/2001/XMLSchema}hexBinary" minOccurs="0"/>
 *                   &lt;element name="Thread_ID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Start_Address" type="{http://www.w3.org/2001/XMLSchema}hexBinary" minOccurs="0"/>
 *                   &lt;element name="Creation_Flags" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="User_Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Target_PID" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Memory_Action_Attributes" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Start_Address" type="{http://www.w3.org/2001/XMLSchema}hexBinary" minOccurs="0"/>
 *                   &lt;element name="Source_Address" type="{http://www.w3.org/2001/XMLSchema}hexBinary" minOccurs="0"/>
 *                   &lt;element name="Destination_Address" type="{http://www.w3.org/2001/XMLSchema}hexBinary" minOccurs="0"/>
 *                   &lt;element name="Page_Base_Address" type="{http://www.w3.org/2001/XMLSchema}hexBinary" minOccurs="0"/>
 *                   &lt;element name="Target_PID" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *                   &lt;element name="Requested_Address" type="{http://www.w3.org/2001/XMLSchema}hexBinary" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Registry_Action_Attributes" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Enumerated_Subkeys" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Enumerated_Values" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Network_Action_Attributes" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Internal_Port" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *                   &lt;element name="External_Port" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *                   &lt;element name="Internal_IP_Address" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="External_IP_Address" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Host_Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Data_Sent" type="{http://maec.mitre.org/XMLSchema/maec-core-1}DataType" minOccurs="0"/>
 *                   &lt;element name="Data_Received" type="{http://maec.mitre.org/XMLSchema/maec-core-1}DataType" minOccurs="0"/>
 *                   &lt;element name="Buffer_Length" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Module_Action_Attributes" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Function_Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Flags" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Daemon_Action_Attributes" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Options" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Start_Type" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Desired_Access_Type" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Enumerated_Daemons" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Daemon_Reference" type="{http://maec.mitre.org/XMLSchema/maec-core-1}ObjectReferenceType" maxOccurs="unbounded"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="System_Action_Attributes" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Computer_Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Local_Time" type="{http://www.w3.org/2001/XMLSchema}time" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Internet_Action_Attributes" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="URL_Connected" type="{http://xml/metadataSharing.xsd}uriObject" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://maec.mitre.org/XMLSchema/maec-core-1}ActionImpIDPattern" />
 *       &lt;attribute name="type">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="API_Call"/>
 *             &lt;enumeration value="Code"/>
 *             &lt;enumeration value="Other"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ActionImplementationType", propOrder = {
    "apiCall",
    "code",
    "platform",
    "dataRead",
    "dataWritten",
    "fileSystemActionAttributes",
    "ipcActionAttributes",
    "processActionAttributes",
    "memoryActionAttributes",
    "registryActionAttributes",
    "networkActionAttributes",
    "moduleActionAttributes",
    "daemonActionAttributes",
    "systemActionAttributes",
    "internetActionAttributes"
})
public class ActionImplementationType {

    @XmlElement(name = "API_Call")
    protected APICallType apiCall;
    @XmlElement(name = "Code")
    protected List<CodeType> code;
    @XmlElement(name = "Platform")
    protected CPESpecificationType platform;
    @XmlElement(name = "Data_Read")
    protected DataType dataRead;
    @XmlElement(name = "Data_Written")
    protected DataType dataWritten;
    @XmlElement(name = "File_System_Action_Attributes")
    protected ActionImplementationType.FileSystemActionAttributes fileSystemActionAttributes;
    @XmlElement(name = "IPC_Action_Attributes")
    protected ActionImplementationType.IPCActionAttributes ipcActionAttributes;
    @XmlElement(name = "Process_Action_Attributes")
    protected ActionImplementationType.ProcessActionAttributes processActionAttributes;
    @XmlElement(name = "Memory_Action_Attributes")
    protected ActionImplementationType.MemoryActionAttributes memoryActionAttributes;
    @XmlElement(name = "Registry_Action_Attributes")
    protected ActionImplementationType.RegistryActionAttributes registryActionAttributes;
    @XmlElement(name = "Network_Action_Attributes")
    protected ActionImplementationType.NetworkActionAttributes networkActionAttributes;
    @XmlElement(name = "Module_Action_Attributes")
    protected ActionImplementationType.ModuleActionAttributes moduleActionAttributes;
    @XmlElement(name = "Daemon_Action_Attributes")
    protected ActionImplementationType.DaemonActionAttributes daemonActionAttributes;
    @XmlElement(name = "System_Action_Attributes")
    protected ActionImplementationType.SystemActionAttributes systemActionAttributes;
    @XmlElement(name = "Internet_Action_Attributes")
    protected ActionImplementationType.InternetActionAttributes internetActionAttributes;
    @XmlAttribute(name = "id", required = true)
    protected String id;
    @XmlAttribute(name = "type")
    protected String type;

    /**
     * Gets the value of the apiCall property.
     * 
     * @return
     *     possible object is
     *     {@link APICallType }
     *     
     */
    public APICallType getAPICall() {
        return apiCall;
    }

    /**
     * Sets the value of the apiCall property.
     * 
     * @param value
     *     allowed object is
     *     {@link APICallType }
     *     
     */
    public void setAPICall(APICallType value) {
        this.apiCall = value;
    }

    /**
     * Gets the value of the code property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the code property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CodeType }
     * 
     * 
     */
    public List<CodeType> getCode() {
        if (code == null) {
            code = new ArrayList<CodeType>();
        }
        return this.code;
    }

    /**
     * Gets the value of the platform property.
     * 
     * @return
     *     possible object is
     *     {@link CPESpecificationType }
     *     
     */
    public CPESpecificationType getPlatform() {
        return platform;
    }

    /**
     * Sets the value of the platform property.
     * 
     * @param value
     *     allowed object is
     *     {@link CPESpecificationType }
     *     
     */
    public void setPlatform(CPESpecificationType value) {
        this.platform = value;
    }

    /**
     * Gets the value of the dataRead property.
     * 
     * @return
     *     possible object is
     *     {@link DataType }
     *     
     */
    public DataType getDataRead() {
        return dataRead;
    }

    /**
     * Sets the value of the dataRead property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataType }
     *     
     */
    public void setDataRead(DataType value) {
        this.dataRead = value;
    }

    /**
     * Gets the value of the dataWritten property.
     * 
     * @return
     *     possible object is
     *     {@link DataType }
     *     
     */
    public DataType getDataWritten() {
        return dataWritten;
    }

    /**
     * Sets the value of the dataWritten property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataType }
     *     
     */
    public void setDataWritten(DataType value) {
        this.dataWritten = value;
    }

    /**
     * Gets the value of the fileSystemActionAttributes property.
     * 
     * @return
     *     possible object is
     *     {@link ActionImplementationType.FileSystemActionAttributes }
     *     
     */
    public ActionImplementationType.FileSystemActionAttributes getFileSystemActionAttributes() {
        return fileSystemActionAttributes;
    }

    /**
     * Sets the value of the fileSystemActionAttributes property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActionImplementationType.FileSystemActionAttributes }
     *     
     */
    public void setFileSystemActionAttributes(ActionImplementationType.FileSystemActionAttributes value) {
        this.fileSystemActionAttributes = value;
    }

    /**
     * Gets the value of the ipcActionAttributes property.
     * 
     * @return
     *     possible object is
     *     {@link ActionImplementationType.IPCActionAttributes }
     *     
     */
    public ActionImplementationType.IPCActionAttributes getIPCActionAttributes() {
        return ipcActionAttributes;
    }

    /**
     * Sets the value of the ipcActionAttributes property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActionImplementationType.IPCActionAttributes }
     *     
     */
    public void setIPCActionAttributes(ActionImplementationType.IPCActionAttributes value) {
        this.ipcActionAttributes = value;
    }

    /**
     * Gets the value of the processActionAttributes property.
     * 
     * @return
     *     possible object is
     *     {@link ActionImplementationType.ProcessActionAttributes }
     *     
     */
    public ActionImplementationType.ProcessActionAttributes getProcessActionAttributes() {
        return processActionAttributes;
    }

    /**
     * Sets the value of the processActionAttributes property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActionImplementationType.ProcessActionAttributes }
     *     
     */
    public void setProcessActionAttributes(ActionImplementationType.ProcessActionAttributes value) {
        this.processActionAttributes = value;
    }

    /**
     * Gets the value of the memoryActionAttributes property.
     * 
     * @return
     *     possible object is
     *     {@link ActionImplementationType.MemoryActionAttributes }
     *     
     */
    public ActionImplementationType.MemoryActionAttributes getMemoryActionAttributes() {
        return memoryActionAttributes;
    }

    /**
     * Sets the value of the memoryActionAttributes property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActionImplementationType.MemoryActionAttributes }
     *     
     */
    public void setMemoryActionAttributes(ActionImplementationType.MemoryActionAttributes value) {
        this.memoryActionAttributes = value;
    }

    /**
     * Gets the value of the registryActionAttributes property.
     * 
     * @return
     *     possible object is
     *     {@link ActionImplementationType.RegistryActionAttributes }
     *     
     */
    public ActionImplementationType.RegistryActionAttributes getRegistryActionAttributes() {
        return registryActionAttributes;
    }

    /**
     * Sets the value of the registryActionAttributes property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActionImplementationType.RegistryActionAttributes }
     *     
     */
    public void setRegistryActionAttributes(ActionImplementationType.RegistryActionAttributes value) {
        this.registryActionAttributes = value;
    }

    /**
     * Gets the value of the networkActionAttributes property.
     * 
     * @return
     *     possible object is
     *     {@link ActionImplementationType.NetworkActionAttributes }
     *     
     */
    public ActionImplementationType.NetworkActionAttributes getNetworkActionAttributes() {
        return networkActionAttributes;
    }

    /**
     * Sets the value of the networkActionAttributes property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActionImplementationType.NetworkActionAttributes }
     *     
     */
    public void setNetworkActionAttributes(ActionImplementationType.NetworkActionAttributes value) {
        this.networkActionAttributes = value;
    }

    /**
     * Gets the value of the moduleActionAttributes property.
     * 
     * @return
     *     possible object is
     *     {@link ActionImplementationType.ModuleActionAttributes }
     *     
     */
    public ActionImplementationType.ModuleActionAttributes getModuleActionAttributes() {
        return moduleActionAttributes;
    }

    /**
     * Sets the value of the moduleActionAttributes property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActionImplementationType.ModuleActionAttributes }
     *     
     */
    public void setModuleActionAttributes(ActionImplementationType.ModuleActionAttributes value) {
        this.moduleActionAttributes = value;
    }

    /**
     * Gets the value of the daemonActionAttributes property.
     * 
     * @return
     *     possible object is
     *     {@link ActionImplementationType.DaemonActionAttributes }
     *     
     */
    public ActionImplementationType.DaemonActionAttributes getDaemonActionAttributes() {
        return daemonActionAttributes;
    }

    /**
     * Sets the value of the daemonActionAttributes property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActionImplementationType.DaemonActionAttributes }
     *     
     */
    public void setDaemonActionAttributes(ActionImplementationType.DaemonActionAttributes value) {
        this.daemonActionAttributes = value;
    }

    /**
     * Gets the value of the systemActionAttributes property.
     * 
     * @return
     *     possible object is
     *     {@link ActionImplementationType.SystemActionAttributes }
     *     
     */
    public ActionImplementationType.SystemActionAttributes getSystemActionAttributes() {
        return systemActionAttributes;
    }

    /**
     * Sets the value of the systemActionAttributes property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActionImplementationType.SystemActionAttributes }
     *     
     */
    public void setSystemActionAttributes(ActionImplementationType.SystemActionAttributes value) {
        this.systemActionAttributes = value;
    }

    /**
     * Gets the value of the internetActionAttributes property.
     * 
     * @return
     *     possible object is
     *     {@link ActionImplementationType.InternetActionAttributes }
     *     
     */
    public ActionImplementationType.InternetActionAttributes getInternetActionAttributes() {
        return internetActionAttributes;
    }

    /**
     * Sets the value of the internetActionAttributes property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActionImplementationType.InternetActionAttributes }
     *     
     */
    public void setInternetActionAttributes(ActionImplementationType.InternetActionAttributes value) {
        this.internetActionAttributes = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Options" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Start_Type" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Desired_Access_Type" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Enumerated_Daemons" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Daemon_Reference" type="{http://maec.mitre.org/XMLSchema/maec-core-1}ObjectReferenceType" maxOccurs="unbounded"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "options",
        "startType",
        "desiredAccessType",
        "enumeratedDaemons"
    })
    public static class DaemonActionAttributes {

        @XmlElement(name = "Options")
        protected String options;
        @XmlElement(name = "Start_Type")
        protected String startType;
        @XmlElement(name = "Desired_Access_Type")
        protected String desiredAccessType;
        @XmlElement(name = "Enumerated_Daemons")
        protected ActionImplementationType.DaemonActionAttributes.EnumeratedDaemons enumeratedDaemons;

        /**
         * Gets the value of the options property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOptions() {
            return options;
        }

        /**
         * Sets the value of the options property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOptions(String value) {
            this.options = value;
        }

        /**
         * Gets the value of the startType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getStartType() {
            return startType;
        }

        /**
         * Sets the value of the startType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setStartType(String value) {
            this.startType = value;
        }

        /**
         * Gets the value of the desiredAccessType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDesiredAccessType() {
            return desiredAccessType;
        }

        /**
         * Sets the value of the desiredAccessType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDesiredAccessType(String value) {
            this.desiredAccessType = value;
        }

        /**
         * Gets the value of the enumeratedDaemons property.
         * 
         * @return
         *     possible object is
         *     {@link ActionImplementationType.DaemonActionAttributes.EnumeratedDaemons }
         *     
         */
        public ActionImplementationType.DaemonActionAttributes.EnumeratedDaemons getEnumeratedDaemons() {
            return enumeratedDaemons;
        }

        /**
         * Sets the value of the enumeratedDaemons property.
         * 
         * @param value
         *     allowed object is
         *     {@link ActionImplementationType.DaemonActionAttributes.EnumeratedDaemons }
         *     
         */
        public void setEnumeratedDaemons(ActionImplementationType.DaemonActionAttributes.EnumeratedDaemons value) {
            this.enumeratedDaemons = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Daemon_Reference" type="{http://maec.mitre.org/XMLSchema/maec-core-1}ObjectReferenceType" maxOccurs="unbounded"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "daemonReference"
        })
        public static class EnumeratedDaemons {

            @XmlElement(name = "Daemon_Reference", required = true)
            protected List<ObjectReferenceType> daemonReference;

            /**
             * Gets the value of the daemonReference property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the daemonReference property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getDaemonReference().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link ObjectReferenceType }
             * 
             * 
             */
            public List<ObjectReferenceType> getDaemonReference() {
                if (daemonReference == null) {
                    daemonReference = new ArrayList<ObjectReferenceType>();
                }
                return this.daemonReference;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Existing_File_Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Destination_File_Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Access_Mode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Flags" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Open_Mode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="File_Attributes" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "existingFileName",
        "destinationFileName",
        "accessMode",
        "flags",
        "openMode",
        "fileAttributes"
    })
    public static class FileSystemActionAttributes {

        @XmlElement(name = "Existing_File_Name")
        protected String existingFileName;
        @XmlElement(name = "Destination_File_Name")
        protected String destinationFileName;
        @XmlElement(name = "Access_Mode")
        protected String accessMode;
        @XmlElement(name = "Flags")
        protected String flags;
        @XmlElement(name = "Open_Mode")
        protected String openMode;
        @XmlElement(name = "File_Attributes")
        protected String fileAttributes;

        /**
         * Gets the value of the existingFileName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getExistingFileName() {
            return existingFileName;
        }

        /**
         * Sets the value of the existingFileName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setExistingFileName(String value) {
            this.existingFileName = value;
        }

        /**
         * Gets the value of the destinationFileName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDestinationFileName() {
            return destinationFileName;
        }

        /**
         * Sets the value of the destinationFileName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDestinationFileName(String value) {
            this.destinationFileName = value;
        }

        /**
         * Gets the value of the accessMode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAccessMode() {
            return accessMode;
        }

        /**
         * Sets the value of the accessMode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAccessMode(String value) {
            this.accessMode = value;
        }

        /**
         * Gets the value of the flags property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFlags() {
            return flags;
        }

        /**
         * Sets the value of the flags property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFlags(String value) {
            this.flags = value;
        }

        /**
         * Gets the value of the openMode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOpenMode() {
            return openMode;
        }

        /**
         * Sets the value of the openMode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOpenMode(String value) {
            this.openMode = value;
        }

        /**
         * Gets the value of the fileAttributes property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFileAttributes() {
            return fileAttributes;
        }

        /**
         * Sets the value of the fileAttributes property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFileAttributes(String value) {
            this.fileAttributes = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Initial_Owner" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Thread_ID" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *         &lt;element name="Target_PID" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *         &lt;element name="Start_Address" type="{http://www.w3.org/2001/XMLSchema}hexBinary" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "initialOwner",
        "threadID",
        "targetPID",
        "startAddress"
    })
    public static class IPCActionAttributes {

        @XmlElement(name = "Initial_Owner")
        protected String initialOwner;
        @XmlElement(name = "Thread_ID")
        protected Integer threadID;
        @XmlElement(name = "Target_PID")
        protected Integer targetPID;
        @XmlElement(name = "Start_Address", type = String.class)
        @XmlJavaTypeAdapter(HexBinaryAdapter.class)
        @XmlSchemaType(name = "hexBinary")
        protected byte[] startAddress;

        /**
         * Gets the value of the initialOwner property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getInitialOwner() {
            return initialOwner;
        }

        /**
         * Sets the value of the initialOwner property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setInitialOwner(String value) {
            this.initialOwner = value;
        }

        /**
         * Gets the value of the threadID property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getThreadID() {
            return threadID;
        }

        /**
         * Sets the value of the threadID property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setThreadID(Integer value) {
            this.threadID = value;
        }

        /**
         * Gets the value of the targetPID property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getTargetPID() {
            return targetPID;
        }

        /**
         * Sets the value of the targetPID property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setTargetPID(Integer value) {
            this.targetPID = value;
        }

        /**
         * Gets the value of the startAddress property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public byte[] getStartAddress() {
            return startAddress;
        }

        /**
         * Sets the value of the startAddress property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setStartAddress(byte[] value) {
            this.startAddress = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="URL_Connected" type="{http://xml/metadataSharing.xsd}uriObject" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "urlConnected"
    })
    public static class InternetActionAttributes {

        @XmlElement(name = "URL_Connected")
        protected UriObject urlConnected;

        /**
         * Gets the value of the urlConnected property.
         * 
         * @return
         *     possible object is
         *     {@link UriObject }
         *     
         */
        public UriObject getURLConnected() {
            return urlConnected;
        }

        /**
         * Sets the value of the urlConnected property.
         * 
         * @param value
         *     allowed object is
         *     {@link UriObject }
         *     
         */
        public void setURLConnected(UriObject value) {
            this.urlConnected = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Start_Address" type="{http://www.w3.org/2001/XMLSchema}hexBinary" minOccurs="0"/>
     *         &lt;element name="Source_Address" type="{http://www.w3.org/2001/XMLSchema}hexBinary" minOccurs="0"/>
     *         &lt;element name="Destination_Address" type="{http://www.w3.org/2001/XMLSchema}hexBinary" minOccurs="0"/>
     *         &lt;element name="Page_Base_Address" type="{http://www.w3.org/2001/XMLSchema}hexBinary" minOccurs="0"/>
     *         &lt;element name="Target_PID" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *         &lt;element name="Requested_Address" type="{http://www.w3.org/2001/XMLSchema}hexBinary" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "startAddress",
        "sourceAddress",
        "destinationAddress",
        "pageBaseAddress",
        "targetPID",
        "requestedAddress"
    })
    public static class MemoryActionAttributes {

        @XmlElement(name = "Start_Address", type = String.class)
        @XmlJavaTypeAdapter(HexBinaryAdapter.class)
        @XmlSchemaType(name = "hexBinary")
        protected byte[] startAddress;
        @XmlElement(name = "Source_Address", type = String.class)
        @XmlJavaTypeAdapter(HexBinaryAdapter.class)
        @XmlSchemaType(name = "hexBinary")
        protected byte[] sourceAddress;
        @XmlElement(name = "Destination_Address", type = String.class)
        @XmlJavaTypeAdapter(HexBinaryAdapter.class)
        @XmlSchemaType(name = "hexBinary")
        protected byte[] destinationAddress;
        @XmlElement(name = "Page_Base_Address", type = String.class)
        @XmlJavaTypeAdapter(HexBinaryAdapter.class)
        @XmlSchemaType(name = "hexBinary")
        protected byte[] pageBaseAddress;
        @XmlElement(name = "Target_PID")
        protected Integer targetPID;
        @XmlElement(name = "Requested_Address", type = String.class)
        @XmlJavaTypeAdapter(HexBinaryAdapter.class)
        @XmlSchemaType(name = "hexBinary")
        protected byte[] requestedAddress;

        /**
         * Gets the value of the startAddress property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public byte[] getStartAddress() {
            return startAddress;
        }

        /**
         * Sets the value of the startAddress property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setStartAddress(byte[] value) {
            this.startAddress = value;
        }

        /**
         * Gets the value of the sourceAddress property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public byte[] getSourceAddress() {
            return sourceAddress;
        }

        /**
         * Sets the value of the sourceAddress property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSourceAddress(byte[] value) {
            this.sourceAddress = value;
        }

        /**
         * Gets the value of the destinationAddress property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public byte[] getDestinationAddress() {
            return destinationAddress;
        }

        /**
         * Sets the value of the destinationAddress property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDestinationAddress(byte[] value) {
            this.destinationAddress = value;
        }

        /**
         * Gets the value of the pageBaseAddress property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public byte[] getPageBaseAddress() {
            return pageBaseAddress;
        }

        /**
         * Sets the value of the pageBaseAddress property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPageBaseAddress(byte[] value) {
            this.pageBaseAddress = value;
        }

        /**
         * Gets the value of the targetPID property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getTargetPID() {
            return targetPID;
        }

        /**
         * Sets the value of the targetPID property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setTargetPID(Integer value) {
            this.targetPID = value;
        }

        /**
         * Gets the value of the requestedAddress property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public byte[] getRequestedAddress() {
            return requestedAddress;
        }

        /**
         * Sets the value of the requestedAddress property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRequestedAddress(byte[] value) {
            this.requestedAddress = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Function_Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Flags" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "functionName",
        "flags"
    })
    public static class ModuleActionAttributes {

        @XmlElement(name = "Function_Name")
        protected String functionName;
        @XmlElement(name = "Flags")
        protected String flags;

        /**
         * Gets the value of the functionName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFunctionName() {
            return functionName;
        }

        /**
         * Sets the value of the functionName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFunctionName(String value) {
            this.functionName = value;
        }

        /**
         * Gets the value of the flags property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFlags() {
            return flags;
        }

        /**
         * Sets the value of the flags property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFlags(String value) {
            this.flags = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Internal_Port" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *         &lt;element name="External_Port" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *         &lt;element name="Internal_IP_Address" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="External_IP_Address" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Host_Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Data_Sent" type="{http://maec.mitre.org/XMLSchema/maec-core-1}DataType" minOccurs="0"/>
     *         &lt;element name="Data_Received" type="{http://maec.mitre.org/XMLSchema/maec-core-1}DataType" minOccurs="0"/>
     *         &lt;element name="Buffer_Length" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "internalPort",
        "externalPort",
        "internalIPAddress",
        "externalIPAddress",
        "hostName",
        "dataSent",
        "dataReceived",
        "bufferLength"
    })
    public static class NetworkActionAttributes {

        @XmlElement(name = "Internal_Port")
        protected Integer internalPort;
        @XmlElement(name = "External_Port")
        protected Integer externalPort;
        @XmlElement(name = "Internal_IP_Address")
        protected String internalIPAddress;
        @XmlElement(name = "External_IP_Address")
        protected String externalIPAddress;
        @XmlElement(name = "Host_Name")
        protected String hostName;
        @XmlElement(name = "Data_Sent")
        protected DataType dataSent;
        @XmlElement(name = "Data_Received")
        protected DataType dataReceived;
        @XmlElement(name = "Buffer_Length")
        protected Integer bufferLength;

        /**
         * Gets the value of the internalPort property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getInternalPort() {
            return internalPort;
        }

        /**
         * Sets the value of the internalPort property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setInternalPort(Integer value) {
            this.internalPort = value;
        }

        /**
         * Gets the value of the externalPort property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getExternalPort() {
            return externalPort;
        }

        /**
         * Sets the value of the externalPort property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setExternalPort(Integer value) {
            this.externalPort = value;
        }

        /**
         * Gets the value of the internalIPAddress property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getInternalIPAddress() {
            return internalIPAddress;
        }

        /**
         * Sets the value of the internalIPAddress property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setInternalIPAddress(String value) {
            this.internalIPAddress = value;
        }

        /**
         * Gets the value of the externalIPAddress property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getExternalIPAddress() {
            return externalIPAddress;
        }

        /**
         * Sets the value of the externalIPAddress property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setExternalIPAddress(String value) {
            this.externalIPAddress = value;
        }

        /**
         * Gets the value of the hostName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHostName() {
            return hostName;
        }

        /**
         * Sets the value of the hostName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHostName(String value) {
            this.hostName = value;
        }

        /**
         * Gets the value of the dataSent property.
         * 
         * @return
         *     possible object is
         *     {@link DataType }
         *     
         */
        public DataType getDataSent() {
            return dataSent;
        }

        /**
         * Sets the value of the dataSent property.
         * 
         * @param value
         *     allowed object is
         *     {@link DataType }
         *     
         */
        public void setDataSent(DataType value) {
            this.dataSent = value;
        }

        /**
         * Gets the value of the dataReceived property.
         * 
         * @return
         *     possible object is
         *     {@link DataType }
         *     
         */
        public DataType getDataReceived() {
            return dataReceived;
        }

        /**
         * Sets the value of the dataReceived property.
         * 
         * @param value
         *     allowed object is
         *     {@link DataType }
         *     
         */
        public void setDataReceived(DataType value) {
            this.dataReceived = value;
        }

        /**
         * Gets the value of the bufferLength property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getBufferLength() {
            return bufferLength;
        }

        /**
         * Sets the value of the bufferLength property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setBufferLength(Integer value) {
            this.bufferLength = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Process_Base_Address" type="{http://www.w3.org/2001/XMLSchema}hexBinary" minOccurs="0"/>
     *         &lt;element name="Thread_ID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Start_Address" type="{http://www.w3.org/2001/XMLSchema}hexBinary" minOccurs="0"/>
     *         &lt;element name="Creation_Flags" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="User_Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Target_PID" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "processBaseAddress",
        "threadID",
        "startAddress",
        "creationFlags",
        "userName",
        "targetPID"
    })
    public static class ProcessActionAttributes {

        @XmlElement(name = "Process_Base_Address", type = String.class)
        @XmlJavaTypeAdapter(HexBinaryAdapter.class)
        @XmlSchemaType(name = "hexBinary")
        protected byte[] processBaseAddress;
        @XmlElement(name = "Thread_ID")
        protected String threadID;
        @XmlElement(name = "Start_Address", type = String.class)
        @XmlJavaTypeAdapter(HexBinaryAdapter.class)
        @XmlSchemaType(name = "hexBinary")
        protected byte[] startAddress;
        @XmlElement(name = "Creation_Flags")
        protected String creationFlags;
        @XmlElement(name = "User_Name")
        protected String userName;
        @XmlElement(name = "Target_PID")
        protected Integer targetPID;

        /**
         * Gets the value of the processBaseAddress property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public byte[] getProcessBaseAddress() {
            return processBaseAddress;
        }

        /**
         * Sets the value of the processBaseAddress property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setProcessBaseAddress(byte[] value) {
            this.processBaseAddress = value;
        }

        /**
         * Gets the value of the threadID property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getThreadID() {
            return threadID;
        }

        /**
         * Sets the value of the threadID property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setThreadID(String value) {
            this.threadID = value;
        }

        /**
         * Gets the value of the startAddress property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public byte[] getStartAddress() {
            return startAddress;
        }

        /**
         * Sets the value of the startAddress property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setStartAddress(byte[] value) {
            this.startAddress = value;
        }

        /**
         * Gets the value of the creationFlags property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCreationFlags() {
            return creationFlags;
        }

        /**
         * Sets the value of the creationFlags property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCreationFlags(String value) {
            this.creationFlags = value;
        }

        /**
         * Gets the value of the userName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUserName() {
            return userName;
        }

        /**
         * Sets the value of the userName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUserName(String value) {
            this.userName = value;
        }

        /**
         * Gets the value of the targetPID property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getTargetPID() {
            return targetPID;
        }

        /**
         * Sets the value of the targetPID property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setTargetPID(Integer value) {
            this.targetPID = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Enumerated_Subkeys" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Enumerated_Values" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "enumeratedSubkeys",
        "enumeratedValues"
    })
    public static class RegistryActionAttributes {

        @XmlElement(name = "Enumerated_Subkeys")
        protected String enumeratedSubkeys;
        @XmlElement(name = "Enumerated_Values")
        protected String enumeratedValues;

        /**
         * Gets the value of the enumeratedSubkeys property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEnumeratedSubkeys() {
            return enumeratedSubkeys;
        }

        /**
         * Sets the value of the enumeratedSubkeys property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEnumeratedSubkeys(String value) {
            this.enumeratedSubkeys = value;
        }

        /**
         * Gets the value of the enumeratedValues property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEnumeratedValues() {
            return enumeratedValues;
        }

        /**
         * Sets the value of the enumeratedValues property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEnumeratedValues(String value) {
            this.enumeratedValues = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Computer_Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Local_Time" type="{http://www.w3.org/2001/XMLSchema}time" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "computerName",
        "localTime"
    })
    public static class SystemActionAttributes {

        @XmlElement(name = "Computer_Name")
        protected String computerName;
        @XmlElement(name = "Local_Time")
        @XmlSchemaType(name = "time")
        protected XMLGregorianCalendar localTime;

        /**
         * Gets the value of the computerName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getComputerName() {
            return computerName;
        }

        /**
         * Sets the value of the computerName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setComputerName(String value) {
            this.computerName = value;
        }

        /**
         * Gets the value of the localTime property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getLocalTime() {
            return localTime;
        }

        /**
         * Sets the value of the localTime property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setLocalTime(XMLGregorianCalendar value) {
            this.localTime = value;
        }

    }

}
