//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.25 at 10:39:55 PM BST 
//


package org.mitre.maec.xmlschema.maec_core_1;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ActionTypeEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ActionTypeEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Login/Logon"/>
 *     &lt;enumeration value="Logout/Logoff"/>
 *     &lt;enumeration value="Start"/>
 *     &lt;enumeration value="Stop"/>
 *     &lt;enumeration value="Suspend/Pause"/>
 *     &lt;enumeration value="Resume"/>
 *     &lt;enumeration value="Create"/>
 *     &lt;enumeration value="Remove/Delete"/>
 *     &lt;enumeration value="Access/Open"/>
 *     &lt;enumeration value="Close"/>
 *     &lt;enumeration value="Move"/>
 *     &lt;enumeration value="Copy/Duplicate"/>
 *     &lt;enumeration value="Read"/>
 *     &lt;enumeration value="Write"/>
 *     &lt;enumeration value="Execute"/>
 *     &lt;enumeration value="Quarantine"/>
 *     &lt;enumeration value="Find"/>
 *     &lt;enumeration value="Clean"/>
 *     &lt;enumeration value="Block"/>
 *     &lt;enumeration value="Update"/>
 *     &lt;enumeration value="Upgrade"/>
 *     &lt;enumeration value="Scan"/>
 *     &lt;enumeration value="Filter"/>
 *     &lt;enumeration value="Install"/>
 *     &lt;enumeration value="Allocate"/>
 *     &lt;enumeration value="Initialize"/>
 *     &lt;enumeration value="Save"/>
 *     &lt;enumeration value="Connect"/>
 *     &lt;enumeration value="Disconnect"/>
 *     &lt;enumeration value="Audit"/>
 *     &lt;enumeration value="Replicate"/>
 *     &lt;enumeration value="Detect"/>
 *     &lt;enumeration value="Alert"/>
 *     &lt;enumeration value="Backup"/>
 *     &lt;enumeration value="Search"/>
 *     &lt;enumeration value="Restore"/>
 *     &lt;enumeration value="Get"/>
 *     &lt;enumeration value="Set"/>
 *     &lt;enumeration value="Assign"/>
 *     &lt;enumeration value="Send"/>
 *     &lt;enumeration value="Receive"/>
 *     &lt;enumeration value="Transmit"/>
 *     &lt;enumeration value="Map"/>
 *     &lt;enumeration value="Load"/>
 *     &lt;enumeration value="Query"/>
 *     &lt;enumeration value="Enumerate"/>
 *     &lt;enumeration value="Bind"/>
 *     &lt;enumeration value="Free"/>
 *     &lt;enumeration value="Kill"/>
 *     &lt;enumeration value="Encrypt"/>
 *     &lt;enumeration value="Decrypt"/>
 *     &lt;enumeration value="Encode"/>
 *     &lt;enumeration value="Decode"/>
 *     &lt;enumeration value="Pack"/>
 *     &lt;enumeration value="Unpack"/>
 *     &lt;enumeration value="Archive"/>
 *     &lt;enumeration value="Compress"/>
 *     &lt;enumeration value="Decompress"/>
 *     &lt;enumeration value="Download"/>
 *     &lt;enumeration value="Upload"/>
 *     &lt;enumeration value="Load"/>
 *     &lt;enumeration value="Fork"/>
 *     &lt;enumeration value="Join"/>
 *     &lt;enumeration value="Merge"/>
 *     &lt;enumeration value="Interleave"/>
 *     &lt;enumeration value="Schedule"/>
 *     &lt;enumeration value="Call"/>
 *     &lt;enumeration value="Compare"/>
 *     &lt;enumeration value="Wipe/Destroy/Purge"/>
 *     &lt;enumeration value="Throw/Raise"/>
 *     &lt;enumeration value="Lock"/>
 *     &lt;enumeration value="Unlock"/>
 *     &lt;enumeration value="Synchronize"/>
 *     &lt;enumeration value="Hook"/>
 *     &lt;enumeration value="Unhook"/>
 *     &lt;enumeration value="Draw"/>
 *     &lt;enumeration value="Click"/>
 *     &lt;enumeration value="Press"/>
 *     &lt;enumeration value="Depress"/>
 *     &lt;enumeration value="Close(network)"/>
 *     &lt;enumeration value="Open(network)"/>
 *     &lt;enumeration value="Callback"/>
 *     &lt;enumeration value="Drop"/>
 *     &lt;enumeration value="Accept"/>
 *     &lt;enumeration value="Deny"/>
 *     &lt;enumeration value="Modify"/>
 *     &lt;enumeration value="Listen"/>
 *     &lt;enumeration value="Send"/>
 *     &lt;enumeration value="Start_Winsock"/>
 *     &lt;enumeration value="Other"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ActionTypeEnum")
@XmlEnum
public enum ActionTypeEnum {

    @XmlEnumValue("Login/Logon")
    LOGIN_LOGON("Login/Logon"),
    @XmlEnumValue("Logout/Logoff")
    LOGOUT_LOGOFF("Logout/Logoff"),
    @XmlEnumValue("Start")
    START("Start"),
    @XmlEnumValue("Stop")
    STOP("Stop"),
    @XmlEnumValue("Suspend/Pause")
    SUSPEND_PAUSE("Suspend/Pause"),
    @XmlEnumValue("Resume")
    RESUME("Resume"),
    @XmlEnumValue("Create")
    CREATE("Create"),
    @XmlEnumValue("Remove/Delete")
    REMOVE_DELETE("Remove/Delete"),
    @XmlEnumValue("Access/Open")
    ACCESS_OPEN("Access/Open"),
    @XmlEnumValue("Close")
    CLOSE("Close"),
    @XmlEnumValue("Move")
    MOVE("Move"),
    @XmlEnumValue("Copy/Duplicate")
    COPY_DUPLICATE("Copy/Duplicate"),
    @XmlEnumValue("Read")
    READ("Read"),
    @XmlEnumValue("Write")
    WRITE("Write"),
    @XmlEnumValue("Execute")
    EXECUTE("Execute"),
    @XmlEnumValue("Quarantine")
    QUARANTINE("Quarantine"),
    @XmlEnumValue("Find")
    FIND("Find"),
    @XmlEnumValue("Clean")
    CLEAN("Clean"),
    @XmlEnumValue("Block")
    BLOCK("Block"),
    @XmlEnumValue("Update")
    UPDATE("Update"),
    @XmlEnumValue("Upgrade")
    UPGRADE("Upgrade"),
    @XmlEnumValue("Scan")
    SCAN("Scan"),
    @XmlEnumValue("Filter")
    FILTER("Filter"),
    @XmlEnumValue("Install")
    INSTALL("Install"),
    @XmlEnumValue("Allocate")
    ALLOCATE("Allocate"),
    @XmlEnumValue("Initialize")
    INITIALIZE("Initialize"),
    @XmlEnumValue("Save")
    SAVE("Save"),
    @XmlEnumValue("Connect")
    CONNECT("Connect"),
    @XmlEnumValue("Disconnect")
    DISCONNECT("Disconnect"),
    @XmlEnumValue("Audit")
    AUDIT("Audit"),
    @XmlEnumValue("Replicate")
    REPLICATE("Replicate"),
    @XmlEnumValue("Detect")
    DETECT("Detect"),
    @XmlEnumValue("Alert")
    ALERT("Alert"),
    @XmlEnumValue("Backup")
    BACKUP("Backup"),
    @XmlEnumValue("Search")
    SEARCH("Search"),
    @XmlEnumValue("Restore")
    RESTORE("Restore"),
    @XmlEnumValue("Get")
    GET("Get"),
    @XmlEnumValue("Set")
    SET("Set"),
    @XmlEnumValue("Assign")
    ASSIGN("Assign"),
    @XmlEnumValue("Send")
    SEND("Send"),
    @XmlEnumValue("Receive")
    RECEIVE("Receive"),
    @XmlEnumValue("Transmit")
    TRANSMIT("Transmit"),
    @XmlEnumValue("Map")
    MAP("Map"),
    @XmlEnumValue("Load")
    LOAD("Load"),
    @XmlEnumValue("Query")
    QUERY("Query"),
    @XmlEnumValue("Enumerate")
    ENUMERATE("Enumerate"),
    @XmlEnumValue("Bind")
    BIND("Bind"),
    @XmlEnumValue("Free")
    FREE("Free"),
    @XmlEnumValue("Kill")
    KILL("Kill"),
    @XmlEnumValue("Encrypt")
    ENCRYPT("Encrypt"),
    @XmlEnumValue("Decrypt")
    DECRYPT("Decrypt"),
    @XmlEnumValue("Encode")
    ENCODE("Encode"),
    @XmlEnumValue("Decode")
    DECODE("Decode"),
    @XmlEnumValue("Pack")
    PACK("Pack"),
    @XmlEnumValue("Unpack")
    UNPACK("Unpack"),
    @XmlEnumValue("Archive")
    ARCHIVE("Archive"),
    @XmlEnumValue("Compress")
    COMPRESS("Compress"),
    @XmlEnumValue("Decompress")
    DECOMPRESS("Decompress"),
    @XmlEnumValue("Download")
    DOWNLOAD("Download"),
    @XmlEnumValue("Upload")
    UPLOAD("Upload"),
    @XmlEnumValue("Fork")
    FORK("Fork"),
    @XmlEnumValue("Join")
    JOIN("Join"),
    @XmlEnumValue("Merge")
    MERGE("Merge"),
    @XmlEnumValue("Interleave")
    INTERLEAVE("Interleave"),
    @XmlEnumValue("Schedule")
    SCHEDULE("Schedule"),
    @XmlEnumValue("Call")
    CALL("Call"),
    @XmlEnumValue("Compare")
    COMPARE("Compare"),
    @XmlEnumValue("Wipe/Destroy/Purge")
    WIPE_DESTROY_PURGE("Wipe/Destroy/Purge"),
    @XmlEnumValue("Throw/Raise")
    THROW_RAISE("Throw/Raise"),
    @XmlEnumValue("Lock")
    LOCK("Lock"),
    @XmlEnumValue("Unlock")
    UNLOCK("Unlock"),
    @XmlEnumValue("Synchronize")
    SYNCHRONIZE("Synchronize"),
    @XmlEnumValue("Hook")
    HOOK("Hook"),
    @XmlEnumValue("Unhook")
    UNHOOK("Unhook"),
    @XmlEnumValue("Draw")
    DRAW("Draw"),
    @XmlEnumValue("Click")
    CLICK("Click"),
    @XmlEnumValue("Press")
    PRESS("Press"),
    @XmlEnumValue("Depress")
    DEPRESS("Depress"),
    @XmlEnumValue("Close(network)")
    CLOSE_NETWORK("Close(network)"),
    @XmlEnumValue("Open(network)")
    OPEN_NETWORK("Open(network)"),
    @XmlEnumValue("Callback")
    CALLBACK("Callback"),
    @XmlEnumValue("Drop")
    DROP("Drop"),
    @XmlEnumValue("Accept")
    ACCEPT("Accept"),
    @XmlEnumValue("Deny")
    DENY("Deny"),
    @XmlEnumValue("Modify")
    MODIFY("Modify"),
    @XmlEnumValue("Listen")
    LISTEN("Listen"),
    @XmlEnumValue("Start_Winsock")
    START_WINSOCK("Start_Winsock"),
    @XmlEnumValue("Other")
    OTHER("Other");
    private final String value;

    ActionTypeEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ActionTypeEnum fromValue(String v) {
        for (ActionTypeEnum c: ActionTypeEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
