//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.25 at 10:39:55 PM BST 
//


package org.mitre.maec.xmlschema.maec_core_1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import xml.metadatasharing.FieldDataEntry;
import xml.metadatasharing.UriObject;


/**
 * AnalysisType is intended to provide a way of characterizing typical malware analysis-related metadata, such as the subject of the analysis and when it was started.
 * 
 * <p>Java class for AnalysisType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AnalysisType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Subject" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="URI" type="{http://xml/metadataSharing.xsd}uriObject" minOccurs="0"/>
 *                   &lt;element name="Object_Reference" type="{http://maec.mitre.org/XMLSchema/maec-core-1}ObjectReferenceType" minOccurs="0"/>
 *                   &lt;element name="Object" type="{http://maec.mitre.org/XMLSchema/maec-core-1}ObjectType" minOccurs="0"/>
 *                   &lt;element name="Subject_Field_Data" type="{http://xml/metadataSharing.xsd}fieldDataEntry" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Description" type="{http://maec.mitre.org/XMLSchema/maec-core-1}StructuredTextType" minOccurs="0"/>
 *         &lt;element name="Analysts" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Analyst" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Source" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Organization_Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="POC" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="URI" type="{http://xml/metadataSharing.xsd}uriObject" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Analysis_Environment" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="OS" type="{http://maec.mitre.org/XMLSchema/maec-core-1}CPESpecificationType" minOccurs="0"/>
 *                   &lt;element name="Enivironment_Variables" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Environment_Variable" maxOccurs="unbounded">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="Value" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Tools_Used" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Tool" type="{http://maec.mitre.org/XMLSchema/maec-core-1}ToolType" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Notes" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Note" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://maec.mitre.org/XMLSchema/maec-core-1}AnalysisIDPattern" />
 *       &lt;attribute name="analysis_method">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="Static"/>
 *             &lt;enumeration value="Dynamic"/>
 *             &lt;enumeration value="Combinatorial"/>
 *             &lt;enumeration value="Other"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="start_datetime" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="complete_datetime" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="lastupdate_datetime" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AnalysisType", propOrder = {
    "subject",
    "description",
    "analysts",
    "source",
    "analysisEnvironment",
    "toolsUsed",
    "notes"
})
public class AnalysisType {

    @XmlElement(name = "Subject", required = true)
    protected List<AnalysisType.Subject> subject;
    @XmlElement(name = "Description")
    protected StructuredTextType description;
    @XmlElement(name = "Analysts")
    protected AnalysisType.Analysts analysts;
    @XmlElement(name = "Source")
    protected AnalysisType.Source source;
    @XmlElement(name = "Analysis_Environment")
    protected AnalysisType.AnalysisEnvironment analysisEnvironment;
    @XmlElement(name = "Tools_Used")
    protected AnalysisType.ToolsUsed toolsUsed;
    @XmlElement(name = "Notes")
    protected AnalysisType.Notes notes;
    @XmlAttribute(name = "id", required = true)
    protected String id;
    @XmlAttribute(name = "analysis_method")
    protected String analysisMethod;
    @XmlAttribute(name = "start_datetime")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar startDatetime;
    @XmlAttribute(name = "complete_datetime")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar completeDatetime;
    @XmlAttribute(name = "lastupdate_datetime")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar lastupdateDatetime;

    /**
     * Gets the value of the subject property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the subject property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSubject().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AnalysisType.Subject }
     * 
     * 
     */
    public List<AnalysisType.Subject> getSubject() {
        if (subject == null) {
            subject = new ArrayList<AnalysisType.Subject>();
        }
        return this.subject;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link StructuredTextType }
     *     
     */
    public StructuredTextType getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link StructuredTextType }
     *     
     */
    public void setDescription(StructuredTextType value) {
        this.description = value;
    }

    /**
     * Gets the value of the analysts property.
     * 
     * @return
     *     possible object is
     *     {@link AnalysisType.Analysts }
     *     
     */
    public AnalysisType.Analysts getAnalysts() {
        return analysts;
    }

    /**
     * Sets the value of the analysts property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnalysisType.Analysts }
     *     
     */
    public void setAnalysts(AnalysisType.Analysts value) {
        this.analysts = value;
    }

    /**
     * Gets the value of the source property.
     * 
     * @return
     *     possible object is
     *     {@link AnalysisType.Source }
     *     
     */
    public AnalysisType.Source getSource() {
        return source;
    }

    /**
     * Sets the value of the source property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnalysisType.Source }
     *     
     */
    public void setSource(AnalysisType.Source value) {
        this.source = value;
    }

    /**
     * Gets the value of the analysisEnvironment property.
     * 
     * @return
     *     possible object is
     *     {@link AnalysisType.AnalysisEnvironment }
     *     
     */
    public AnalysisType.AnalysisEnvironment getAnalysisEnvironment() {
        return analysisEnvironment;
    }

    /**
     * Sets the value of the analysisEnvironment property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnalysisType.AnalysisEnvironment }
     *     
     */
    public void setAnalysisEnvironment(AnalysisType.AnalysisEnvironment value) {
        this.analysisEnvironment = value;
    }

    /**
     * Gets the value of the toolsUsed property.
     * 
     * @return
     *     possible object is
     *     {@link AnalysisType.ToolsUsed }
     *     
     */
    public AnalysisType.ToolsUsed getToolsUsed() {
        return toolsUsed;
    }

    /**
     * Sets the value of the toolsUsed property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnalysisType.ToolsUsed }
     *     
     */
    public void setToolsUsed(AnalysisType.ToolsUsed value) {
        this.toolsUsed = value;
    }

    /**
     * Gets the value of the notes property.
     * 
     * @return
     *     possible object is
     *     {@link AnalysisType.Notes }
     *     
     */
    public AnalysisType.Notes getNotes() {
        return notes;
    }

    /**
     * Sets the value of the notes property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnalysisType.Notes }
     *     
     */
    public void setNotes(AnalysisType.Notes value) {
        this.notes = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the analysisMethod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAnalysisMethod() {
        return analysisMethod;
    }

    /**
     * Sets the value of the analysisMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAnalysisMethod(String value) {
        this.analysisMethod = value;
    }

    /**
     * Gets the value of the startDatetime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getStartDatetime() {
        return startDatetime;
    }

    /**
     * Sets the value of the startDatetime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setStartDatetime(XMLGregorianCalendar value) {
        this.startDatetime = value;
    }

    /**
     * Gets the value of the completeDatetime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCompleteDatetime() {
        return completeDatetime;
    }

    /**
     * Sets the value of the completeDatetime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCompleteDatetime(XMLGregorianCalendar value) {
        this.completeDatetime = value;
    }

    /**
     * Gets the value of the lastupdateDatetime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLastupdateDatetime() {
        return lastupdateDatetime;
    }

    /**
     * Sets the value of the lastupdateDatetime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLastupdateDatetime(XMLGregorianCalendar value) {
        this.lastupdateDatetime = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="OS" type="{http://maec.mitre.org/XMLSchema/maec-core-1}CPESpecificationType" minOccurs="0"/>
     *         &lt;element name="Enivironment_Variables" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Environment_Variable" maxOccurs="unbounded">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="Value" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "os",
        "enivironmentVariables"
    })
    public static class AnalysisEnvironment {

        @XmlElement(name = "OS")
        protected CPESpecificationType os;
        @XmlElement(name = "Enivironment_Variables")
        protected AnalysisType.AnalysisEnvironment.EnivironmentVariables enivironmentVariables;

        /**
         * Gets the value of the os property.
         * 
         * @return
         *     possible object is
         *     {@link CPESpecificationType }
         *     
         */
        public CPESpecificationType getOS() {
            return os;
        }

        /**
         * Sets the value of the os property.
         * 
         * @param value
         *     allowed object is
         *     {@link CPESpecificationType }
         *     
         */
        public void setOS(CPESpecificationType value) {
            this.os = value;
        }

        /**
         * Gets the value of the enivironmentVariables property.
         * 
         * @return
         *     possible object is
         *     {@link AnalysisType.AnalysisEnvironment.EnivironmentVariables }
         *     
         */
        public AnalysisType.AnalysisEnvironment.EnivironmentVariables getEnivironmentVariables() {
            return enivironmentVariables;
        }

        /**
         * Sets the value of the enivironmentVariables property.
         * 
         * @param value
         *     allowed object is
         *     {@link AnalysisType.AnalysisEnvironment.EnivironmentVariables }
         *     
         */
        public void setEnivironmentVariables(AnalysisType.AnalysisEnvironment.EnivironmentVariables value) {
            this.enivironmentVariables = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Environment_Variable" maxOccurs="unbounded">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="Value" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "environmentVariable"
        })
        public static class EnivironmentVariables {

            @XmlElement(name = "Environment_Variable", required = true)
            protected List<AnalysisType.AnalysisEnvironment.EnivironmentVariables.EnvironmentVariable> environmentVariable;

            /**
             * Gets the value of the environmentVariable property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the environmentVariable property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getEnvironmentVariable().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link AnalysisType.AnalysisEnvironment.EnivironmentVariables.EnvironmentVariable }
             * 
             * 
             */
            public List<AnalysisType.AnalysisEnvironment.EnivironmentVariables.EnvironmentVariable> getEnvironmentVariable() {
                if (environmentVariable == null) {
                    environmentVariable = new ArrayList<AnalysisType.AnalysisEnvironment.EnivironmentVariables.EnvironmentVariable>();
                }
                return this.environmentVariable;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="Value" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "name",
                "value"
            })
            public static class EnvironmentVariable {

                @XmlElement(name = "Name", required = true)
                protected String name;
                @XmlElement(name = "Value", required = true)
                protected String value;

                /**
                 * Gets the value of the name property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getName() {
                    return name;
                }

                /**
                 * Sets the value of the name property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setName(String value) {
                    this.name = value;
                }

                /**
                 * Gets the value of the value property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setValue(String value) {
                    this.value = value;
                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Analyst" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "analyst"
    })
    public static class Analysts {

        @XmlElement(name = "Analyst", required = true)
        protected List<String> analyst;

        /**
         * Gets the value of the analyst property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the analyst property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAnalyst().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getAnalyst() {
            if (analyst == null) {
                analyst = new ArrayList<String>();
            }
            return this.analyst;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Note" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "note"
    })
    public static class Notes {

        @XmlElement(name = "Note", required = true)
        protected List<String> note;

        /**
         * Gets the value of the note property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the note property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getNote().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getNote() {
            if (note == null) {
                note = new ArrayList<String>();
            }
            return this.note;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Organization_Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="POC" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="URI" type="{http://xml/metadataSharing.xsd}uriObject" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "organizationName",
        "poc",
        "uri"
    })
    public static class Source {

        @XmlElement(name = "Organization_Name")
        protected String organizationName;
        @XmlElement(name = "POC")
        protected String poc;
        @XmlElement(name = "URI")
        protected UriObject uri;

        /**
         * Gets the value of the organizationName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOrganizationName() {
            return organizationName;
        }

        /**
         * Sets the value of the organizationName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOrganizationName(String value) {
            this.organizationName = value;
        }

        /**
         * Gets the value of the poc property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPOC() {
            return poc;
        }

        /**
         * Sets the value of the poc property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPOC(String value) {
            this.poc = value;
        }

        /**
         * Gets the value of the uri property.
         * 
         * @return
         *     possible object is
         *     {@link UriObject }
         *     
         */
        public UriObject getURI() {
            return uri;
        }

        /**
         * Sets the value of the uri property.
         * 
         * @param value
         *     allowed object is
         *     {@link UriObject }
         *     
         */
        public void setURI(UriObject value) {
            this.uri = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="URI" type="{http://xml/metadataSharing.xsd}uriObject" minOccurs="0"/>
     *         &lt;element name="Object_Reference" type="{http://maec.mitre.org/XMLSchema/maec-core-1}ObjectReferenceType" minOccurs="0"/>
     *         &lt;element name="Object" type="{http://maec.mitre.org/XMLSchema/maec-core-1}ObjectType" minOccurs="0"/>
     *         &lt;element name="Subject_Field_Data" type="{http://xml/metadataSharing.xsd}fieldDataEntry" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "uri",
        "objectReference",
        "object",
        "subjectFieldData"
    })
    public static class Subject {

        @XmlElement(name = "URI")
        protected UriObject uri;
        @XmlElement(name = "Object_Reference")
        protected ObjectReferenceType objectReference;
        @XmlElement(name = "Object")
        protected ObjectType object;
        @XmlElement(name = "Subject_Field_Data")
        protected FieldDataEntry subjectFieldData;

        /**
         * Gets the value of the uri property.
         * 
         * @return
         *     possible object is
         *     {@link UriObject }
         *     
         */
        public UriObject getURI() {
            return uri;
        }

        /**
         * Sets the value of the uri property.
         * 
         * @param value
         *     allowed object is
         *     {@link UriObject }
         *     
         */
        public void setURI(UriObject value) {
            this.uri = value;
        }

        /**
         * Gets the value of the objectReference property.
         * 
         * @return
         *     possible object is
         *     {@link ObjectReferenceType }
         *     
         */
        public ObjectReferenceType getObjectReference() {
            return objectReference;
        }

        /**
         * Sets the value of the objectReference property.
         * 
         * @param value
         *     allowed object is
         *     {@link ObjectReferenceType }
         *     
         */
        public void setObjectReference(ObjectReferenceType value) {
            this.objectReference = value;
        }

        /**
         * Gets the value of the object property.
         * 
         * @return
         *     possible object is
         *     {@link ObjectType }
         *     
         */
        public ObjectType getObject() {
            return object;
        }

        /**
         * Sets the value of the object property.
         * 
         * @param value
         *     allowed object is
         *     {@link ObjectType }
         *     
         */
        public void setObject(ObjectType value) {
            this.object = value;
        }

        /**
         * Gets the value of the subjectFieldData property.
         * 
         * @return
         *     possible object is
         *     {@link FieldDataEntry }
         *     
         */
        public FieldDataEntry getSubjectFieldData() {
            return subjectFieldData;
        }

        /**
         * Sets the value of the subjectFieldData property.
         * 
         * @param value
         *     allowed object is
         *     {@link FieldDataEntry }
         *     
         */
        public void setSubjectFieldData(FieldDataEntry value) {
            this.subjectFieldData = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Tool" type="{http://maec.mitre.org/XMLSchema/maec-core-1}ToolType" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "tool"
    })
    public static class ToolsUsed {

        @XmlElement(name = "Tool", required = true)
        protected List<ToolType> tool;

        /**
         * Gets the value of the tool property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the tool property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getTool().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ToolType }
         * 
         * 
         */
        public List<ToolType> getTool() {
            if (tool == null) {
                tool = new ArrayList<ToolType>();
            }
            return this.tool;
        }

    }

}
