//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.25 at 10:39:55 PM BST 
//


package org.mitre.maec.xmlschema.maec_core_1;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.Duration;


/**
 * BehaviorType is intended to serve as a method for the characterization of malicious behaviors found or observed in malware. Behaviors can be thought of as representing the purpose behind groups of MAEC actions, and are therefore representative of distinct portions of higher-level malware functionality. Thus, while a malware instance may perform some thousands of actions, it is likely that these actions represent only a few dozen distinct behaviors. Some examples include vulnerability exploitation, email address harvesting, and the disabling of a security service.
 * 
 * <p>Java class for BehaviorType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BehaviorType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Purpose" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Description" type="{http://maec.mitre.org/XMLSchema/maec-core-1}StructuredTextType" minOccurs="0"/>
 *                   &lt;element name="Attempted_Vulnerability_Exploit" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Known_Exploit" type="{http://maec.mitre.org/XMLSchema/maec-core-1}CVEVulnerabilityType"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="vulnerability_type">
 *                             &lt;simpleType>
 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                 &lt;enumeration value="Known"/>
 *                                 &lt;enumeration value="Unknown"/>
 *                               &lt;/restriction>
 *                             &lt;/simpleType>
 *                           &lt;/attribute>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Description" type="{http://maec.mitre.org/XMLSchema/maec-core-1}StructuredTextType" minOccurs="0"/>
 *         &lt;element name="Discovery_Method" type="{http://maec.mitre.org/XMLSchema/maec-core-1}DiscoveryMethod" minOccurs="0"/>
 *         &lt;element name="Actions" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice maxOccurs="unbounded">
 *                   &lt;element name="Action_Collection" type="{http://maec.mitre.org/XMLSchema/maec-core-1}ActionCollectionType" minOccurs="0"/>
 *                   &lt;element name="Action" type="{http://maec.mitre.org/XMLSchema/maec-core-1}ActionType" minOccurs="0"/>
 *                   &lt;element name="Action_Reference" type="{http://maec.mitre.org/XMLSchema/maec-core-1}ActionReferenceType" minOccurs="0"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Objects" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Object_Reference" type="{http://maec.mitre.org/XMLSchema/maec-core-1}ObjectReferenceType" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="Object" type="{http://maec.mitre.org/XMLSchema/maec-core-1}ObjectType" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Effects" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Effect" type="{http://maec.mitre.org/XMLSchema/maec-core-1}EffectType" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="Effect_Reference" type="{http://maec.mitre.org/XMLSchema/maec-core-1}EffectReferenceType" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Related_Behaviors" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Related_Behavior" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Behavior_Reference" type="{http://maec.mitre.org/XMLSchema/maec-core-1}BehaviorReferenceType"/>
 *                             &lt;element name="Nature_of_Relationship">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;enumeration value="Preceding_Dependency"/>
 *                                   &lt;enumeration value="Coexistence_Dependency"/>
 *                                   &lt;enumeration value="Other"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://maec.mitre.org/XMLSchema/maec-core-1}BehaviorIDPattern" />
 *       &lt;attribute name="ordinal_position" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
 *       &lt;attribute name="successful" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="duration" type="{http://www.w3.org/2001/XMLSchema}duration" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BehaviorType", propOrder = {
    "purpose",
    "description",
    "discoveryMethod",
    "actions",
    "objects",
    "effects",
    "relatedBehaviors"
})
public class BehaviorType {

    @XmlElement(name = "Purpose")
    protected BehaviorType.Purpose purpose;
    @XmlElement(name = "Description")
    protected StructuredTextType description;
    @XmlElement(name = "Discovery_Method")
    protected DiscoveryMethod discoveryMethod;
    @XmlElement(name = "Actions")
    protected BehaviorType.Actions actions;
    @XmlElement(name = "Objects")
    protected BehaviorType.Objects objects;
    @XmlElement(name = "Effects")
    protected BehaviorType.Effects effects;
    @XmlElement(name = "Related_Behaviors")
    protected BehaviorType.RelatedBehaviors relatedBehaviors;
    @XmlAttribute(name = "id", required = true)
    protected String id;
    @XmlAttribute(name = "ordinal_position")
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger ordinalPosition;
    @XmlAttribute(name = "successful")
    protected Boolean successful;
    @XmlAttribute(name = "duration")
    protected Duration duration;

    /**
     * Gets the value of the purpose property.
     * 
     * @return
     *     possible object is
     *     {@link BehaviorType.Purpose }
     *     
     */
    public BehaviorType.Purpose getPurpose() {
        return purpose;
    }

    /**
     * Sets the value of the purpose property.
     * 
     * @param value
     *     allowed object is
     *     {@link BehaviorType.Purpose }
     *     
     */
    public void setPurpose(BehaviorType.Purpose value) {
        this.purpose = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link StructuredTextType }
     *     
     */
    public StructuredTextType getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link StructuredTextType }
     *     
     */
    public void setDescription(StructuredTextType value) {
        this.description = value;
    }

    /**
     * Gets the value of the discoveryMethod property.
     * 
     * @return
     *     possible object is
     *     {@link DiscoveryMethod }
     *     
     */
    public DiscoveryMethod getDiscoveryMethod() {
        return discoveryMethod;
    }

    /**
     * Sets the value of the discoveryMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link DiscoveryMethod }
     *     
     */
    public void setDiscoveryMethod(DiscoveryMethod value) {
        this.discoveryMethod = value;
    }

    /**
     * Gets the value of the actions property.
     * 
     * @return
     *     possible object is
     *     {@link BehaviorType.Actions }
     *     
     */
    public BehaviorType.Actions getActions() {
        return actions;
    }

    /**
     * Sets the value of the actions property.
     * 
     * @param value
     *     allowed object is
     *     {@link BehaviorType.Actions }
     *     
     */
    public void setActions(BehaviorType.Actions value) {
        this.actions = value;
    }

    /**
     * Gets the value of the objects property.
     * 
     * @return
     *     possible object is
     *     {@link BehaviorType.Objects }
     *     
     */
    public BehaviorType.Objects getObjects() {
        return objects;
    }

    /**
     * Sets the value of the objects property.
     * 
     * @param value
     *     allowed object is
     *     {@link BehaviorType.Objects }
     *     
     */
    public void setObjects(BehaviorType.Objects value) {
        this.objects = value;
    }

    /**
     * Gets the value of the effects property.
     * 
     * @return
     *     possible object is
     *     {@link BehaviorType.Effects }
     *     
     */
    public BehaviorType.Effects getEffects() {
        return effects;
    }

    /**
     * Sets the value of the effects property.
     * 
     * @param value
     *     allowed object is
     *     {@link BehaviorType.Effects }
     *     
     */
    public void setEffects(BehaviorType.Effects value) {
        this.effects = value;
    }

    /**
     * Gets the value of the relatedBehaviors property.
     * 
     * @return
     *     possible object is
     *     {@link BehaviorType.RelatedBehaviors }
     *     
     */
    public BehaviorType.RelatedBehaviors getRelatedBehaviors() {
        return relatedBehaviors;
    }

    /**
     * Sets the value of the relatedBehaviors property.
     * 
     * @param value
     *     allowed object is
     *     {@link BehaviorType.RelatedBehaviors }
     *     
     */
    public void setRelatedBehaviors(BehaviorType.RelatedBehaviors value) {
        this.relatedBehaviors = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the ordinalPosition property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getOrdinalPosition() {
        return ordinalPosition;
    }

    /**
     * Sets the value of the ordinalPosition property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setOrdinalPosition(BigInteger value) {
        this.ordinalPosition = value;
    }

    /**
     * Gets the value of the successful property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSuccessful() {
        return successful;
    }

    /**
     * Sets the value of the successful property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSuccessful(Boolean value) {
        this.successful = value;
    }

    /**
     * Gets the value of the duration property.
     * 
     * @return
     *     possible object is
     *     {@link Duration }
     *     
     */
    public Duration getDuration() {
        return duration;
    }

    /**
     * Sets the value of the duration property.
     * 
     * @param value
     *     allowed object is
     *     {@link Duration }
     *     
     */
    public void setDuration(Duration value) {
        this.duration = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice maxOccurs="unbounded">
     *         &lt;element name="Action_Collection" type="{http://maec.mitre.org/XMLSchema/maec-core-1}ActionCollectionType" minOccurs="0"/>
     *         &lt;element name="Action" type="{http://maec.mitre.org/XMLSchema/maec-core-1}ActionType" minOccurs="0"/>
     *         &lt;element name="Action_Reference" type="{http://maec.mitre.org/XMLSchema/maec-core-1}ActionReferenceType" minOccurs="0"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "actionCollectionOrActionOrActionReference"
    })
    public static class Actions {

        @XmlElements({
            @XmlElement(name = "Action_Collection", type = ActionCollectionType.class),
            @XmlElement(name = "Action", type = ActionType.class),
            @XmlElement(name = "Action_Reference", type = ActionReferenceType.class)
        })
        protected List<Object> actionCollectionOrActionOrActionReference;

        /**
         * Gets the value of the actionCollectionOrActionOrActionReference property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the actionCollectionOrActionOrActionReference property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getActionCollectionOrActionOrActionReference().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ActionCollectionType }
         * {@link ActionType }
         * {@link ActionReferenceType }
         * 
         * 
         */
        public List<Object> getActionCollectionOrActionOrActionReference() {
            if (actionCollectionOrActionOrActionReference == null) {
                actionCollectionOrActionOrActionReference = new ArrayList<Object>();
            }
            return this.actionCollectionOrActionOrActionReference;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Effect" type="{http://maec.mitre.org/XMLSchema/maec-core-1}EffectType" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="Effect_Reference" type="{http://maec.mitre.org/XMLSchema/maec-core-1}EffectReferenceType" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "effect",
        "effectReference"
    })
    public static class Effects {

        @XmlElement(name = "Effect")
        protected List<EffectType> effect;
        @XmlElement(name = "Effect_Reference")
        protected List<EffectReferenceType> effectReference;

        /**
         * Gets the value of the effect property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the effect property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getEffect().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link EffectType }
         * 
         * 
         */
        public List<EffectType> getEffect() {
            if (effect == null) {
                effect = new ArrayList<EffectType>();
            }
            return this.effect;
        }

        /**
         * Gets the value of the effectReference property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the effectReference property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getEffectReference().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link EffectReferenceType }
         * 
         * 
         */
        public List<EffectReferenceType> getEffectReference() {
            if (effectReference == null) {
                effectReference = new ArrayList<EffectReferenceType>();
            }
            return this.effectReference;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Object_Reference" type="{http://maec.mitre.org/XMLSchema/maec-core-1}ObjectReferenceType" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="Object" type="{http://maec.mitre.org/XMLSchema/maec-core-1}ObjectType" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "objectReference",
        "object"
    })
    public static class Objects {

        @XmlElement(name = "Object_Reference")
        protected List<ObjectReferenceType> objectReference;
        @XmlElement(name = "Object")
        protected List<ObjectType> object;

        /**
         * Gets the value of the objectReference property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the objectReference property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getObjectReference().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ObjectReferenceType }
         * 
         * 
         */
        public List<ObjectReferenceType> getObjectReference() {
            if (objectReference == null) {
                objectReference = new ArrayList<ObjectReferenceType>();
            }
            return this.objectReference;
        }

        /**
         * Gets the value of the object property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the object property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getObject().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ObjectType }
         * 
         * 
         */
        public List<ObjectType> getObject() {
            if (object == null) {
                object = new ArrayList<ObjectType>();
            }
            return this.object;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Description" type="{http://maec.mitre.org/XMLSchema/maec-core-1}StructuredTextType" minOccurs="0"/>
     *         &lt;element name="Attempted_Vulnerability_Exploit" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Known_Exploit" type="{http://maec.mitre.org/XMLSchema/maec-core-1}CVEVulnerabilityType"/>
     *                 &lt;/sequence>
     *                 &lt;attribute name="vulnerability_type">
     *                   &lt;simpleType>
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                       &lt;enumeration value="Known"/>
     *                       &lt;enumeration value="Unknown"/>
     *                     &lt;/restriction>
     *                   &lt;/simpleType>
     *                 &lt;/attribute>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "description",
        "attemptedVulnerabilityExploit"
    })
    public static class Purpose {

        @XmlElement(name = "Description")
        protected StructuredTextType description;
        @XmlElement(name = "Attempted_Vulnerability_Exploit")
        protected BehaviorType.Purpose.AttemptedVulnerabilityExploit attemptedVulnerabilityExploit;

        /**
         * Gets the value of the description property.
         * 
         * @return
         *     possible object is
         *     {@link StructuredTextType }
         *     
         */
        public StructuredTextType getDescription() {
            return description;
        }

        /**
         * Sets the value of the description property.
         * 
         * @param value
         *     allowed object is
         *     {@link StructuredTextType }
         *     
         */
        public void setDescription(StructuredTextType value) {
            this.description = value;
        }

        /**
         * Gets the value of the attemptedVulnerabilityExploit property.
         * 
         * @return
         *     possible object is
         *     {@link BehaviorType.Purpose.AttemptedVulnerabilityExploit }
         *     
         */
        public BehaviorType.Purpose.AttemptedVulnerabilityExploit getAttemptedVulnerabilityExploit() {
            return attemptedVulnerabilityExploit;
        }

        /**
         * Sets the value of the attemptedVulnerabilityExploit property.
         * 
         * @param value
         *     allowed object is
         *     {@link BehaviorType.Purpose.AttemptedVulnerabilityExploit }
         *     
         */
        public void setAttemptedVulnerabilityExploit(BehaviorType.Purpose.AttemptedVulnerabilityExploit value) {
            this.attemptedVulnerabilityExploit = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Known_Exploit" type="{http://maec.mitre.org/XMLSchema/maec-core-1}CVEVulnerabilityType"/>
         *       &lt;/sequence>
         *       &lt;attribute name="vulnerability_type">
         *         &lt;simpleType>
         *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *             &lt;enumeration value="Known"/>
         *             &lt;enumeration value="Unknown"/>
         *           &lt;/restriction>
         *         &lt;/simpleType>
         *       &lt;/attribute>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "knownExploit"
        })
        public static class AttemptedVulnerabilityExploit {

            @XmlElement(name = "Known_Exploit", required = true)
            protected CVEVulnerabilityType knownExploit;
            @XmlAttribute(name = "vulnerability_type")
            protected String vulnerabilityType;

            /**
             * Gets the value of the knownExploit property.
             * 
             * @return
             *     possible object is
             *     {@link CVEVulnerabilityType }
             *     
             */
            public CVEVulnerabilityType getKnownExploit() {
                return knownExploit;
            }

            /**
             * Sets the value of the knownExploit property.
             * 
             * @param value
             *     allowed object is
             *     {@link CVEVulnerabilityType }
             *     
             */
            public void setKnownExploit(CVEVulnerabilityType value) {
                this.knownExploit = value;
            }

            /**
             * Gets the value of the vulnerabilityType property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getVulnerabilityType() {
                return vulnerabilityType;
            }

            /**
             * Sets the value of the vulnerabilityType property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setVulnerabilityType(String value) {
                this.vulnerabilityType = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Related_Behavior" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Behavior_Reference" type="{http://maec.mitre.org/XMLSchema/maec-core-1}BehaviorReferenceType"/>
     *                   &lt;element name="Nature_of_Relationship">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;enumeration value="Preceding_Dependency"/>
     *                         &lt;enumeration value="Coexistence_Dependency"/>
     *                         &lt;enumeration value="Other"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "relatedBehavior"
    })
    public static class RelatedBehaviors {

        @XmlElement(name = "Related_Behavior", required = true)
        protected List<BehaviorType.RelatedBehaviors.RelatedBehavior> relatedBehavior;

        /**
         * Gets the value of the relatedBehavior property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the relatedBehavior property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getRelatedBehavior().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link BehaviorType.RelatedBehaviors.RelatedBehavior }
         * 
         * 
         */
        public List<BehaviorType.RelatedBehaviors.RelatedBehavior> getRelatedBehavior() {
            if (relatedBehavior == null) {
                relatedBehavior = new ArrayList<BehaviorType.RelatedBehaviors.RelatedBehavior>();
            }
            return this.relatedBehavior;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Behavior_Reference" type="{http://maec.mitre.org/XMLSchema/maec-core-1}BehaviorReferenceType"/>
         *         &lt;element name="Nature_of_Relationship">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;enumeration value="Preceding_Dependency"/>
         *               &lt;enumeration value="Coexistence_Dependency"/>
         *               &lt;enumeration value="Other"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "behaviorReference",
            "natureOfRelationship"
        })
        public static class RelatedBehavior {

            @XmlElement(name = "Behavior_Reference", required = true)
            protected BehaviorReferenceType behaviorReference;
            @XmlElement(name = "Nature_of_Relationship", required = true)
            protected String natureOfRelationship;

            /**
             * Gets the value of the behaviorReference property.
             * 
             * @return
             *     possible object is
             *     {@link BehaviorReferenceType }
             *     
             */
            public BehaviorReferenceType getBehaviorReference() {
                return behaviorReference;
            }

            /**
             * Sets the value of the behaviorReference property.
             * 
             * @param value
             *     allowed object is
             *     {@link BehaviorReferenceType }
             *     
             */
            public void setBehaviorReference(BehaviorReferenceType value) {
                this.behaviorReference = value;
            }

            /**
             * Gets the value of the natureOfRelationship property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNatureOfRelationship() {
                return natureOfRelationship;
            }

            /**
             * Sets the value of the natureOfRelationship property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNatureOfRelationship(String value) {
                this.natureOfRelationship = value;
            }

        }

    }

}
