//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.25 at 10:39:55 PM BST 
//


package org.mitre.maec.xmlschema.maec_core_1;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * BundleType is intended to serve as the high-level construct under which all other MAEC elements reside. 
 * 
 * <p>Java class for BundleType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BundleType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Analyses" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Analysis" type="{http://maec.mitre.org/XMLSchema/maec-core-1}AnalysisType" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Behaviors" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Behavior" type="{http://maec.mitre.org/XMLSchema/maec-core-1}BehaviorType" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Actions" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Action" type="{http://maec.mitre.org/XMLSchema/maec-core-1}ActionType" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Pools" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Behavior_Collection_Pool" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Behavior_Collection" type="{http://maec.mitre.org/XMLSchema/maec-core-1}BehaviorCollectionType" maxOccurs="unbounded"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="Behavior_Pool" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Behavior" type="{http://maec.mitre.org/XMLSchema/maec-core-1}BehaviorType" maxOccurs="unbounded"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="Action_Collection_Pool" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Action_Collection" type="{http://maec.mitre.org/XMLSchema/maec-core-1}ActionCollectionType" maxOccurs="unbounded"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="Action_Pool" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Action" type="{http://maec.mitre.org/XMLSchema/maec-core-1}ActionType" maxOccurs="unbounded"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="Object_Pool" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Object" type="{http://maec.mitre.org/XMLSchema/maec-core-1}ObjectType" maxOccurs="unbounded"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="Effect_Pool" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Effect" type="{http://maec.mitre.org/XMLSchema/maec-core-1}EffectType" maxOccurs="unbounded"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="Object_Collection_Pool" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Object_Collection" type="{http://maec.mitre.org/XMLSchema/maec-core-1}ObjectCollectionType" maxOccurs="unbounded"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://maec.mitre.org/XMLSchema/maec-core-1}BundleIDPattern" />
 *       &lt;attribute name="schema_version" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BundleType", propOrder = {
    "analyses",
    "behaviors",
    "actions",
    "pools"
})
public class BundleType {

    @XmlElement(name = "Analyses")
    protected BundleType.Analyses analyses;
    @XmlElement(name = "Behaviors")
    protected BundleType.Behaviors behaviors;
    @XmlElement(name = "Actions")
    protected BundleType.Actions actions;
    @XmlElement(name = "Pools")
    protected BundleType.Pools pools;
    @XmlAttribute(name = "id", required = true)
    protected String id;
    @XmlAttribute(name = "schema_version", required = true)
    protected BigDecimal schemaVersion;

    /**
     * Gets the value of the analyses property.
     * 
     * @return
     *     possible object is
     *     {@link BundleType.Analyses }
     *     
     */
    public BundleType.Analyses getAnalyses() {
        return analyses;
    }

    /**
     * Sets the value of the analyses property.
     * 
     * @param value
     *     allowed object is
     *     {@link BundleType.Analyses }
     *     
     */
    public void setAnalyses(BundleType.Analyses value) {
        this.analyses = value;
    }

    /**
     * Gets the value of the behaviors property.
     * 
     * @return
     *     possible object is
     *     {@link BundleType.Behaviors }
     *     
     */
    public BundleType.Behaviors getBehaviors() {
        return behaviors;
    }

    /**
     * Sets the value of the behaviors property.
     * 
     * @param value
     *     allowed object is
     *     {@link BundleType.Behaviors }
     *     
     */
    public void setBehaviors(BundleType.Behaviors value) {
        this.behaviors = value;
    }

    /**
     * Gets the value of the actions property.
     * 
     * @return
     *     possible object is
     *     {@link BundleType.Actions }
     *     
     */
    public BundleType.Actions getActions() {
        return actions;
    }

    /**
     * Sets the value of the actions property.
     * 
     * @param value
     *     allowed object is
     *     {@link BundleType.Actions }
     *     
     */
    public void setActions(BundleType.Actions value) {
        this.actions = value;
    }

    /**
     * Gets the value of the pools property.
     * 
     * @return
     *     possible object is
     *     {@link BundleType.Pools }
     *     
     */
    public BundleType.Pools getPools() {
        return pools;
    }

    /**
     * Sets the value of the pools property.
     * 
     * @param value
     *     allowed object is
     *     {@link BundleType.Pools }
     *     
     */
    public void setPools(BundleType.Pools value) {
        this.pools = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the schemaVersion property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSchemaVersion() {
        return schemaVersion;
    }

    /**
     * Sets the value of the schemaVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSchemaVersion(BigDecimal value) {
        this.schemaVersion = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Action" type="{http://maec.mitre.org/XMLSchema/maec-core-1}ActionType" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "action"
    })
    public static class Actions {

        @XmlElement(name = "Action", required = true)
        protected List<ActionType> action;

        /**
         * Gets the value of the action property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the action property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAction().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ActionType }
         * 
         * 
         */
        public List<ActionType> getAction() {
            if (action == null) {
                action = new ArrayList<ActionType>();
            }
            return this.action;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Analysis" type="{http://maec.mitre.org/XMLSchema/maec-core-1}AnalysisType" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "analysis"
    })
    public static class Analyses {

        @XmlElement(name = "Analysis", required = true)
        protected List<AnalysisType> analysis;

        /**
         * Gets the value of the analysis property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the analysis property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAnalysis().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link AnalysisType }
         * 
         * 
         */
        public List<AnalysisType> getAnalysis() {
            if (analysis == null) {
                analysis = new ArrayList<AnalysisType>();
            }
            return this.analysis;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Behavior" type="{http://maec.mitre.org/XMLSchema/maec-core-1}BehaviorType" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "behavior"
    })
    public static class Behaviors {

        @XmlElement(name = "Behavior", required = true)
        protected List<BehaviorType> behavior;

        /**
         * Gets the value of the behavior property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the behavior property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getBehavior().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link BehaviorType }
         * 
         * 
         */
        public List<BehaviorType> getBehavior() {
            if (behavior == null) {
                behavior = new ArrayList<BehaviorType>();
            }
            return this.behavior;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Behavior_Collection_Pool" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Behavior_Collection" type="{http://maec.mitre.org/XMLSchema/maec-core-1}BehaviorCollectionType" maxOccurs="unbounded"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Behavior_Pool" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Behavior" type="{http://maec.mitre.org/XMLSchema/maec-core-1}BehaviorType" maxOccurs="unbounded"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Action_Collection_Pool" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Action_Collection" type="{http://maec.mitre.org/XMLSchema/maec-core-1}ActionCollectionType" maxOccurs="unbounded"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Action_Pool" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Action" type="{http://maec.mitre.org/XMLSchema/maec-core-1}ActionType" maxOccurs="unbounded"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Object_Pool" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Object" type="{http://maec.mitre.org/XMLSchema/maec-core-1}ObjectType" maxOccurs="unbounded"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Effect_Pool" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Effect" type="{http://maec.mitre.org/XMLSchema/maec-core-1}EffectType" maxOccurs="unbounded"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Object_Collection_Pool" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Object_Collection" type="{http://maec.mitre.org/XMLSchema/maec-core-1}ObjectCollectionType" maxOccurs="unbounded"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "behaviorCollectionPool",
        "behaviorPool",
        "actionCollectionPool",
        "actionPool",
        "objectPool",
        "effectPool",
        "objectCollectionPool"
    })
    public static class Pools {

        @XmlElement(name = "Behavior_Collection_Pool")
        protected BundleType.Pools.BehaviorCollectionPool behaviorCollectionPool;
        @XmlElement(name = "Behavior_Pool")
        protected BundleType.Pools.BehaviorPool behaviorPool;
        @XmlElement(name = "Action_Collection_Pool")
        protected BundleType.Pools.ActionCollectionPool actionCollectionPool;
        @XmlElement(name = "Action_Pool")
        protected BundleType.Pools.ActionPool actionPool;
        @XmlElement(name = "Object_Pool")
        protected BundleType.Pools.ObjectPool objectPool;
        @XmlElement(name = "Effect_Pool")
        protected BundleType.Pools.EffectPool effectPool;
        @XmlElement(name = "Object_Collection_Pool")
        protected BundleType.Pools.ObjectCollectionPool objectCollectionPool;

        /**
         * Gets the value of the behaviorCollectionPool property.
         * 
         * @return
         *     possible object is
         *     {@link BundleType.Pools.BehaviorCollectionPool }
         *     
         */
        public BundleType.Pools.BehaviorCollectionPool getBehaviorCollectionPool() {
            return behaviorCollectionPool;
        }

        /**
         * Sets the value of the behaviorCollectionPool property.
         * 
         * @param value
         *     allowed object is
         *     {@link BundleType.Pools.BehaviorCollectionPool }
         *     
         */
        public void setBehaviorCollectionPool(BundleType.Pools.BehaviorCollectionPool value) {
            this.behaviorCollectionPool = value;
        }

        /**
         * Gets the value of the behaviorPool property.
         * 
         * @return
         *     possible object is
         *     {@link BundleType.Pools.BehaviorPool }
         *     
         */
        public BundleType.Pools.BehaviorPool getBehaviorPool() {
            return behaviorPool;
        }

        /**
         * Sets the value of the behaviorPool property.
         * 
         * @param value
         *     allowed object is
         *     {@link BundleType.Pools.BehaviorPool }
         *     
         */
        public void setBehaviorPool(BundleType.Pools.BehaviorPool value) {
            this.behaviorPool = value;
        }

        /**
         * Gets the value of the actionCollectionPool property.
         * 
         * @return
         *     possible object is
         *     {@link BundleType.Pools.ActionCollectionPool }
         *     
         */
        public BundleType.Pools.ActionCollectionPool getActionCollectionPool() {
            return actionCollectionPool;
        }

        /**
         * Sets the value of the actionCollectionPool property.
         * 
         * @param value
         *     allowed object is
         *     {@link BundleType.Pools.ActionCollectionPool }
         *     
         */
        public void setActionCollectionPool(BundleType.Pools.ActionCollectionPool value) {
            this.actionCollectionPool = value;
        }

        /**
         * Gets the value of the actionPool property.
         * 
         * @return
         *     possible object is
         *     {@link BundleType.Pools.ActionPool }
         *     
         */
        public BundleType.Pools.ActionPool getActionPool() {
            return actionPool;
        }

        /**
         * Sets the value of the actionPool property.
         * 
         * @param value
         *     allowed object is
         *     {@link BundleType.Pools.ActionPool }
         *     
         */
        public void setActionPool(BundleType.Pools.ActionPool value) {
            this.actionPool = value;
        }

        /**
         * Gets the value of the objectPool property.
         * 
         * @return
         *     possible object is
         *     {@link BundleType.Pools.ObjectPool }
         *     
         */
        public BundleType.Pools.ObjectPool getObjectPool() {
            return objectPool;
        }

        /**
         * Sets the value of the objectPool property.
         * 
         * @param value
         *     allowed object is
         *     {@link BundleType.Pools.ObjectPool }
         *     
         */
        public void setObjectPool(BundleType.Pools.ObjectPool value) {
            this.objectPool = value;
        }

        /**
         * Gets the value of the effectPool property.
         * 
         * @return
         *     possible object is
         *     {@link BundleType.Pools.EffectPool }
         *     
         */
        public BundleType.Pools.EffectPool getEffectPool() {
            return effectPool;
        }

        /**
         * Sets the value of the effectPool property.
         * 
         * @param value
         *     allowed object is
         *     {@link BundleType.Pools.EffectPool }
         *     
         */
        public void setEffectPool(BundleType.Pools.EffectPool value) {
            this.effectPool = value;
        }

        /**
         * Gets the value of the objectCollectionPool property.
         * 
         * @return
         *     possible object is
         *     {@link BundleType.Pools.ObjectCollectionPool }
         *     
         */
        public BundleType.Pools.ObjectCollectionPool getObjectCollectionPool() {
            return objectCollectionPool;
        }

        /**
         * Sets the value of the objectCollectionPool property.
         * 
         * @param value
         *     allowed object is
         *     {@link BundleType.Pools.ObjectCollectionPool }
         *     
         */
        public void setObjectCollectionPool(BundleType.Pools.ObjectCollectionPool value) {
            this.objectCollectionPool = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Action_Collection" type="{http://maec.mitre.org/XMLSchema/maec-core-1}ActionCollectionType" maxOccurs="unbounded"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "actionCollection"
        })
        public static class ActionCollectionPool {

            @XmlElement(name = "Action_Collection", required = true)
            protected List<ActionCollectionType> actionCollection;

            /**
             * Gets the value of the actionCollection property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the actionCollection property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getActionCollection().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link ActionCollectionType }
             * 
             * 
             */
            public List<ActionCollectionType> getActionCollection() {
                if (actionCollection == null) {
                    actionCollection = new ArrayList<ActionCollectionType>();
                }
                return this.actionCollection;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Action" type="{http://maec.mitre.org/XMLSchema/maec-core-1}ActionType" maxOccurs="unbounded"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "action"
        })
        public static class ActionPool {

            @XmlElement(name = "Action", required = true)
            protected List<ActionType> action;

            /**
             * Gets the value of the action property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the action property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getAction().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link ActionType }
             * 
             * 
             */
            public List<ActionType> getAction() {
                if (action == null) {
                    action = new ArrayList<ActionType>();
                }
                return this.action;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Behavior_Collection" type="{http://maec.mitre.org/XMLSchema/maec-core-1}BehaviorCollectionType" maxOccurs="unbounded"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "behaviorCollection"
        })
        public static class BehaviorCollectionPool {

            @XmlElement(name = "Behavior_Collection", required = true)
            protected List<BehaviorCollectionType> behaviorCollection;

            /**
             * Gets the value of the behaviorCollection property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the behaviorCollection property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getBehaviorCollection().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link BehaviorCollectionType }
             * 
             * 
             */
            public List<BehaviorCollectionType> getBehaviorCollection() {
                if (behaviorCollection == null) {
                    behaviorCollection = new ArrayList<BehaviorCollectionType>();
                }
                return this.behaviorCollection;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Behavior" type="{http://maec.mitre.org/XMLSchema/maec-core-1}BehaviorType" maxOccurs="unbounded"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "behavior"
        })
        public static class BehaviorPool {

            @XmlElement(name = "Behavior", required = true)
            protected List<BehaviorType> behavior;

            /**
             * Gets the value of the behavior property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the behavior property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getBehavior().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link BehaviorType }
             * 
             * 
             */
            public List<BehaviorType> getBehavior() {
                if (behavior == null) {
                    behavior = new ArrayList<BehaviorType>();
                }
                return this.behavior;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Effect" type="{http://maec.mitre.org/XMLSchema/maec-core-1}EffectType" maxOccurs="unbounded"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "effect"
        })
        public static class EffectPool {

            @XmlElement(name = "Effect", required = true)
            protected List<EffectType> effect;

            /**
             * Gets the value of the effect property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the effect property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getEffect().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link EffectType }
             * 
             * 
             */
            public List<EffectType> getEffect() {
                if (effect == null) {
                    effect = new ArrayList<EffectType>();
                }
                return this.effect;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Object_Collection" type="{http://maec.mitre.org/XMLSchema/maec-core-1}ObjectCollectionType" maxOccurs="unbounded"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "objectCollection"
        })
        public static class ObjectCollectionPool {

            @XmlElement(name = "Object_Collection", required = true)
            protected List<ObjectCollectionType> objectCollection;

            /**
             * Gets the value of the objectCollection property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the objectCollection property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getObjectCollection().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link ObjectCollectionType }
             * 
             * 
             */
            public List<ObjectCollectionType> getObjectCollection() {
                if (objectCollection == null) {
                    objectCollection = new ArrayList<ObjectCollectionType>();
                }
                return this.objectCollection;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Object" type="{http://maec.mitre.org/XMLSchema/maec-core-1}ObjectType" maxOccurs="unbounded"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "object"
        })
        public static class ObjectPool {

            @XmlElement(name = "Object", required = true)
            protected List<ObjectType> object;

            /**
             * Gets the value of the object property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the object property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getObject().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link ObjectType }
             * 
             * 
             */
            public List<ObjectType> getObject() {
                if (object == null) {
                    object = new ArrayList<ObjectType>();
                }
                return this.object;
            }

        }

    }

}
