//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.25 at 10:39:55 PM BST 
//


package org.mitre.maec.xmlschema.maec_core_1;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * CPESpecificationType is a modularized data type intended for
 * 				providing a consistent approach to uniquely specifying the identity of a specific
 * 				platform using the Common Platform Enumeration (CPE) naming standard.
 * 				http://cpe.mitre.org/
 * 
 * <p>Java class for CPESpecificationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CPESpecificationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Title" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="lang" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="meta-item-metadata" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="modification-date" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *                 &lt;attribute name="status" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="nvd-id" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *                 &lt;attribute name="xmlns-meta" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="cpe_name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="xmlns_value" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CPESpecificationType", propOrder = {
    "title",
    "metaItemMetadata"
})
public class CPESpecificationType {

    @XmlElement(name = "Title")
    protected CPESpecificationType.Title title;
    @XmlElement(name = "meta-item-metadata")
    protected CPESpecificationType.MetaItemMetadata metaItemMetadata;
    @XmlAttribute(name = "cpe_name", required = true)
    protected String cpeName;
    @XmlAttribute(name = "xmlns_value", required = true)
    protected String xmlnsValue;

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link CPESpecificationType.Title }
     *     
     */
    public CPESpecificationType.Title getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link CPESpecificationType.Title }
     *     
     */
    public void setTitle(CPESpecificationType.Title value) {
        this.title = value;
    }

    /**
     * Gets the value of the metaItemMetadata property.
     * 
     * @return
     *     possible object is
     *     {@link CPESpecificationType.MetaItemMetadata }
     *     
     */
    public CPESpecificationType.MetaItemMetadata getMetaItemMetadata() {
        return metaItemMetadata;
    }

    /**
     * Sets the value of the metaItemMetadata property.
     * 
     * @param value
     *     allowed object is
     *     {@link CPESpecificationType.MetaItemMetadata }
     *     
     */
    public void setMetaItemMetadata(CPESpecificationType.MetaItemMetadata value) {
        this.metaItemMetadata = value;
    }

    /**
     * Gets the value of the cpeName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCpeName() {
        return cpeName;
    }

    /**
     * Sets the value of the cpeName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCpeName(String value) {
        this.cpeName = value;
    }

    /**
     * Gets the value of the xmlnsValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXmlnsValue() {
        return xmlnsValue;
    }

    /**
     * Sets the value of the xmlnsValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXmlnsValue(String value) {
        this.xmlnsValue = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="modification-date" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
     *       &lt;attribute name="status" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="nvd-id" type="{http://www.w3.org/2001/XMLSchema}integer" />
     *       &lt;attribute name="xmlns-meta" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class MetaItemMetadata {

        @XmlAttribute(name = "modification-date")
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar modificationDate;
        @XmlAttribute(name = "status")
        protected String status;
        @XmlAttribute(name = "nvd-id")
        protected BigInteger nvdId;
        @XmlAttribute(name = "xmlns-meta")
        protected String xmlnsMeta;

        /**
         * Gets the value of the modificationDate property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getModificationDate() {
            return modificationDate;
        }

        /**
         * Sets the value of the modificationDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setModificationDate(XMLGregorianCalendar value) {
            this.modificationDate = value;
        }

        /**
         * Gets the value of the status property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getStatus() {
            return status;
        }

        /**
         * Sets the value of the status property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setStatus(String value) {
            this.status = value;
        }

        /**
         * Gets the value of the nvdId property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getNvdId() {
            return nvdId;
        }

        /**
         * Sets the value of the nvdId property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setNvdId(BigInteger value) {
            this.nvdId = value;
        }

        /**
         * Gets the value of the xmlnsMeta property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getXmlnsMeta() {
            return xmlnsMeta;
        }

        /**
         * Sets the value of the xmlnsMeta property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setXmlnsMeta(String value) {
            this.xmlnsMeta = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="lang" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class Title {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "lang")
        protected String lang;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the lang property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLang() {
            return lang;
        }

        /**
         * Sets the value of the lang property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLang(String value) {
            this.lang = value;
        }

    }

}
