//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.25 at 10:39:55 PM BST 
//


package org.mitre.maec.xmlschema.maec_core_1;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EffectTypeEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="EffectTypeEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Object_Properties_Enumerated"/>
 *     &lt;enumeration value="Object_Downloaded"/>
 *     &lt;enumeration value="Object_Uploaded"/>
 *     &lt;enumeration value="Object_Created"/>
 *     &lt;enumeration value="Object_Read_From"/>
 *     &lt;enumeration value="Object_Written_To"/>
 *     &lt;enumeration value="Object_Loaded_Into_Memory"/>
 *     &lt;enumeration value="Object_Copied"/>
 *     &lt;enumeration value="Object_Deleted"/>
 *     &lt;enumeration value="Object_Moved"/>
 *     &lt;enumeration value="Object_Bound"/>
 *     &lt;enumeration value="Object_Opened"/>
 *     &lt;enumeration value="Object_Queried"/>
 *     &lt;enumeration value="Object_Mapped"/>
 *     &lt;enumeration value="Object_Listened_On"/>
 *     &lt;enumeration value="Object_Properties_Modified"/>
 *     &lt;enumeration value="Object_Values_Enumerated"/>
 *     &lt;enumeration value="Object_Searched_For"/>
 *     &lt;enumeration value="Other"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "EffectTypeEnum")
@XmlEnum
public enum EffectTypeEnum {

    @XmlEnumValue("Object_Properties_Enumerated")
    OBJECT_PROPERTIES_ENUMERATED("Object_Properties_Enumerated"),
    @XmlEnumValue("Object_Downloaded")
    OBJECT_DOWNLOADED("Object_Downloaded"),
    @XmlEnumValue("Object_Uploaded")
    OBJECT_UPLOADED("Object_Uploaded"),
    @XmlEnumValue("Object_Created")
    OBJECT_CREATED("Object_Created"),
    @XmlEnumValue("Object_Read_From")
    OBJECT_READ_FROM("Object_Read_From"),
    @XmlEnumValue("Object_Written_To")
    OBJECT_WRITTEN_TO("Object_Written_To"),
    @XmlEnumValue("Object_Loaded_Into_Memory")
    OBJECT_LOADED_INTO_MEMORY("Object_Loaded_Into_Memory"),
    @XmlEnumValue("Object_Copied")
    OBJECT_COPIED("Object_Copied"),
    @XmlEnumValue("Object_Deleted")
    OBJECT_DELETED("Object_Deleted"),
    @XmlEnumValue("Object_Moved")
    OBJECT_MOVED("Object_Moved"),
    @XmlEnumValue("Object_Bound")
    OBJECT_BOUND("Object_Bound"),
    @XmlEnumValue("Object_Opened")
    OBJECT_OPENED("Object_Opened"),
    @XmlEnumValue("Object_Queried")
    OBJECT_QUERIED("Object_Queried"),
    @XmlEnumValue("Object_Mapped")
    OBJECT_MAPPED("Object_Mapped"),
    @XmlEnumValue("Object_Listened_On")
    OBJECT_LISTENED_ON("Object_Listened_On"),
    @XmlEnumValue("Object_Properties_Modified")
    OBJECT_PROPERTIES_MODIFIED("Object_Properties_Modified"),
    @XmlEnumValue("Object_Values_Enumerated")
    OBJECT_VALUES_ENUMERATED("Object_Values_Enumerated"),
    @XmlEnumValue("Object_Searched_For")
    OBJECT_SEARCHED_FOR("Object_Searched_For"),
    @XmlEnumValue("Other")
    OTHER("Other");
    private final String value;

    EffectTypeEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static EffectTypeEnum fromValue(String v) {
        for (EffectTypeEnum c: EffectTypeEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
