//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.25 at 10:39:55 PM BST 
//


package org.mitre.maec.xmlschema.maec_core_1;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FileTypeEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="FileTypeEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="PE"/>
 *     &lt;enumeration value="JS"/>
 *     &lt;enumeration value="PDF"/>
 *     &lt;enumeration value="ZIP"/>
 *     &lt;enumeration value="TXT"/>
 *     &lt;enumeration value="ASM"/>
 *     &lt;enumeration value="DOC"/>
 *     &lt;enumeration value="DOCX"/>
 *     &lt;enumeration value="XLS"/>
 *     &lt;enumeration value="XLSX"/>
 *     &lt;enumeration value="PPT"/>
 *     &lt;enumeration value="PPTX"/>
 *     &lt;enumeration value="Other"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "FileTypeEnum")
@XmlEnum
public enum FileTypeEnum {

    PE("PE"),
    JS("JS"),
    PDF("PDF"),
    ZIP("ZIP"),
    TXT("TXT"),
    ASM("ASM"),
    DOC("DOC"),
    DOCX("DOCX"),
    XLS("XLS"),
    XLSX("XLSX"),
    PPT("PPT"),
    PPTX("PPTX"),
    @XmlEnumValue("Other")
    OTHER("Other");
    private final String value;

    FileTypeEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static FileTypeEnum fromValue(String v) {
        for (FileTypeEnum c: FileTypeEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
