//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.25 at 10:39:55 PM BST 
//


package org.mitre.maec.xmlschema.maec_core_1;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ObjectTypeEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ObjectTypeEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="File"/>
 *     &lt;enumeration value="Directory"/>
 *     &lt;enumeration value="Module"/>
 *     &lt;enumeration value="Packet"/>
 *     &lt;enumeration value="Key/Key Group"/>
 *     &lt;enumeration value="Hive"/>
 *     &lt;enumeration value="Process"/>
 *     &lt;enumeration value="Thread"/>
 *     &lt;enumeration value="Mutex"/>
 *     &lt;enumeration value="Event"/>
 *     &lt;enumeration value="Service/Daemon"/>
 *     &lt;enumeration value="Library"/>
 *     &lt;enumeration value="Package"/>
 *     &lt;enumeration value="Pipe"/>
 *     &lt;enumeration value="Socket"/>
 *     &lt;enumeration value="IP Address"/>
 *     &lt;enumeration value="Port"/>
 *     &lt;enumeration value="Protocol"/>
 *     &lt;enumeration value="AS"/>
 *     &lt;enumeration value="URI"/>
 *     &lt;enumeration value="Host"/>
 *     &lt;enumeration value="Session"/>
 *     &lt;enumeration value="Session Token"/>
 *     &lt;enumeration value="Account"/>
 *     &lt;enumeration value="Device (physical)"/>
 *     &lt;enumeration value="Handle"/>
 *     &lt;enumeration value="Heap"/>
 *     &lt;enumeration value="Memory Address"/>
 *     &lt;enumeration value="Memory Page"/>
 *     &lt;enumeration value="Window"/>
 *     &lt;enumeration value="Dialog"/>
 *     &lt;enumeration value="Parameter"/>
 *     &lt;enumeration value="Authentication Token"/>
 *     &lt;enumeration value="Encryption Token"/>
 *     &lt;enumeration value="Web Query"/>
 *     &lt;enumeration value="Protocol Header"/>
 *     &lt;enumeration value="Protocol Field"/>
 *     &lt;enumeration value="Link"/>
 *     &lt;enumeration value="SQL Query"/>
 *     &lt;enumeration value="Database"/>
 *     &lt;enumeration value="ACL"/>
 *     &lt;enumeration value="Role"/>
 *     &lt;enumeration value="System"/>
 *     &lt;enumeration value="VM"/>
 *     &lt;enumeration value="Signature"/>
 *     &lt;enumeration value="Channel"/>
 *     &lt;enumeration value="API Call"/>
 *     &lt;enumeration value="Environment Variable"/>
 *     &lt;enumeration value="Application"/>
 *     &lt;enumeration value="Network"/>
 *     &lt;enumeration value="Configuration"/>
 *     &lt;enumeration value="Policy"/>
 *     &lt;enumeration value="Tack"/>
 *     &lt;enumeration value="Malware"/>
 *     &lt;enumeration value="Message"/>
 *     &lt;enumeration value="Email Message"/>
 *     &lt;enumeration value="Media"/>
 *     &lt;enumeration value="Operating System"/>
 *     &lt;enumeration value="Query"/>
 *     &lt;enumeration value="Domain"/>
 *     &lt;enumeration value="Event"/>
 *     &lt;enumeration value="Other"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ObjectTypeEnum")
@XmlEnum
public enum ObjectTypeEnum {

    @XmlEnumValue("File")
    FILE("File"),
    @XmlEnumValue("Directory")
    DIRECTORY("Directory"),
    @XmlEnumValue("Module")
    MODULE("Module"),
    @XmlEnumValue("Packet")
    PACKET("Packet"),
    @XmlEnumValue("Key/Key Group")
    KEY_KEY_GROUP("Key/Key Group"),
    @XmlEnumValue("Hive")
    HIVE("Hive"),
    @XmlEnumValue("Process")
    PROCESS("Process"),
    @XmlEnumValue("Thread")
    THREAD("Thread"),
    @XmlEnumValue("Mutex")
    MUTEX("Mutex"),
    @XmlEnumValue("Event")
    EVENT("Event"),
    @XmlEnumValue("Service/Daemon")
    SERVICE_DAEMON("Service/Daemon"),
    @XmlEnumValue("Library")
    LIBRARY("Library"),
    @XmlEnumValue("Package")
    PACKAGE("Package"),
    @XmlEnumValue("Pipe")
    PIPE("Pipe"),
    @XmlEnumValue("Socket")
    SOCKET("Socket"),
    @XmlEnumValue("IP Address")
    IP_ADDRESS("IP Address"),
    @XmlEnumValue("Port")
    PORT("Port"),
    @XmlEnumValue("Protocol")
    PROTOCOL("Protocol"),
    AS("AS"),
    URI("URI"),
    @XmlEnumValue("Host")
    HOST("Host"),
    @XmlEnumValue("Session")
    SESSION("Session"),
    @XmlEnumValue("Session Token")
    SESSION_TOKEN("Session Token"),
    @XmlEnumValue("Account")
    ACCOUNT("Account"),
    @XmlEnumValue("Device (physical)")
    DEVICE_PHYSICAL("Device (physical)"),
    @XmlEnumValue("Handle")
    HANDLE("Handle"),
    @XmlEnumValue("Heap")
    HEAP("Heap"),
    @XmlEnumValue("Memory Address")
    MEMORY_ADDRESS("Memory Address"),
    @XmlEnumValue("Memory Page")
    MEMORY_PAGE("Memory Page"),
    @XmlEnumValue("Window")
    WINDOW("Window"),
    @XmlEnumValue("Dialog")
    DIALOG("Dialog"),
    @XmlEnumValue("Parameter")
    PARAMETER("Parameter"),
    @XmlEnumValue("Authentication Token")
    AUTHENTICATION_TOKEN("Authentication Token"),
    @XmlEnumValue("Encryption Token")
    ENCRYPTION_TOKEN("Encryption Token"),
    @XmlEnumValue("Web Query")
    WEB_QUERY("Web Query"),
    @XmlEnumValue("Protocol Header")
    PROTOCOL_HEADER("Protocol Header"),
    @XmlEnumValue("Protocol Field")
    PROTOCOL_FIELD("Protocol Field"),
    @XmlEnumValue("Link")
    LINK("Link"),
    @XmlEnumValue("SQL Query")
    SQL_QUERY("SQL Query"),
    @XmlEnumValue("Database")
    DATABASE("Database"),
    ACL("ACL"),
    @XmlEnumValue("Role")
    ROLE("Role"),
    @XmlEnumValue("System")
    SYSTEM("System"),
    VM("VM"),
    @XmlEnumValue("Signature")
    SIGNATURE("Signature"),
    @XmlEnumValue("Channel")
    CHANNEL("Channel"),
    @XmlEnumValue("API Call")
    API_CALL("API Call"),
    @XmlEnumValue("Environment Variable")
    ENVIRONMENT_VARIABLE("Environment Variable"),
    @XmlEnumValue("Application")
    APPLICATION("Application"),
    @XmlEnumValue("Network")
    NETWORK("Network"),
    @XmlEnumValue("Configuration")
    CONFIGURATION("Configuration"),
    @XmlEnumValue("Policy")
    POLICY("Policy"),
    @XmlEnumValue("Tack")
    TACK("Tack"),
    @XmlEnumValue("Malware")
    MALWARE("Malware"),
    @XmlEnumValue("Message")
    MESSAGE("Message"),
    @XmlEnumValue("Email Message")
    EMAIL_MESSAGE("Email Message"),
    @XmlEnumValue("Media")
    MEDIA("Media"),
    @XmlEnumValue("Operating System")
    OPERATING_SYSTEM("Operating System"),
    @XmlEnumValue("Query")
    QUERY("Query"),
    @XmlEnumValue("Domain")
    DOMAIN("Domain"),
    @XmlEnumValue("Other")
    OTHER("Other");
    private final String value;

    ObjectTypeEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ObjectTypeEnum fromValue(String v) {
        for (ObjectTypeEnum c: ObjectTypeEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
