//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.25 at 10:39:55 PM BST 
//


package org.mitre.maec.xmlschema.maec_core_1;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PackerTypeEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="PackerTypeEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Archiver"/>
 *     &lt;enumeration value="Installer"/>
 *     &lt;enumeration value="Self-Extracting Archiver"/>
 *     &lt;enumeration value="Crypter"/>
 *     &lt;enumeration value="Packer"/>
 *     &lt;enumeration value="Protector"/>
 *     &lt;enumeration value="Bundler"/>
 *     &lt;enumeration value="Other"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "PackerTypeEnum")
@XmlEnum
public enum PackerTypeEnum {

    @XmlEnumValue("Archiver")
    ARCHIVER("Archiver"),
    @XmlEnumValue("Installer")
    INSTALLER("Installer"),
    @XmlEnumValue("Self-Extracting Archiver")
    SELF_EXTRACTING_ARCHIVER("Self-Extracting Archiver"),
    @XmlEnumValue("Crypter")
    CRYPTER("Crypter"),
    @XmlEnumValue("Packer")
    PACKER("Packer"),
    @XmlEnumValue("Protector")
    PROTECTOR("Protector"),
    @XmlEnumValue("Bundler")
    BUNDLER("Bundler"),
    @XmlEnumValue("Other")
    OTHER("Other");
    private final String value;

    PackerTypeEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static PackerTypeEnum fromValue(String v) {
        for (PackerTypeEnum c: PackerTypeEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
