//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.25 at 10:39:55 PM BST 
//


package org.mitre.maec.xmlschema.maec_core_1;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.HexBinaryAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * PEImportType is intended as container for the attributes relevant to PE binary imports.
 * 
 * <p>Java class for PEImportType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PEImportType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="File_Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Virtual_Address" type="{http://www.w3.org/2001/XMLSchema}hexBinary" minOccurs="0"/>
 *         &lt;element name="Imported_Functions" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Imported_Function" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Function_Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Virtual_Address" type="{http://www.w3.org/2001/XMLSchema}hexBinary" minOccurs="0"/>
 *                             &lt;element name="Hint" type="{http://www.w3.org/2001/XMLSchema}hexBinary" minOccurs="0"/>
 *                             &lt;element name="Ordinal" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="type">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="Initially visible"/>
 *             &lt;enumeration value="Initially hidden"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="delay_load" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PEImportType", propOrder = {
    "fileName",
    "virtualAddress",
    "importedFunctions"
})
public class PEImportType {

    @XmlElement(name = "File_Name", required = true)
    protected String fileName;
    @XmlElement(name = "Virtual_Address", type = String.class)
    @XmlJavaTypeAdapter(HexBinaryAdapter.class)
    @XmlSchemaType(name = "hexBinary")
    protected byte[] virtualAddress;
    @XmlElement(name = "Imported_Functions")
    protected PEImportType.ImportedFunctions importedFunctions;
    @XmlAttribute(name = "type")
    protected String type;
    @XmlAttribute(name = "delay_load")
    protected Boolean delayLoad;

    /**
     * Gets the value of the fileName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * Sets the value of the fileName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFileName(String value) {
        this.fileName = value;
    }

    /**
     * Gets the value of the virtualAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public byte[] getVirtualAddress() {
        return virtualAddress;
    }

    /**
     * Sets the value of the virtualAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVirtualAddress(byte[] value) {
        this.virtualAddress = value;
    }

    /**
     * Gets the value of the importedFunctions property.
     * 
     * @return
     *     possible object is
     *     {@link PEImportType.ImportedFunctions }
     *     
     */
    public PEImportType.ImportedFunctions getImportedFunctions() {
        return importedFunctions;
    }

    /**
     * Sets the value of the importedFunctions property.
     * 
     * @param value
     *     allowed object is
     *     {@link PEImportType.ImportedFunctions }
     *     
     */
    public void setImportedFunctions(PEImportType.ImportedFunctions value) {
        this.importedFunctions = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the delayLoad property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDelayLoad() {
        return delayLoad;
    }

    /**
     * Sets the value of the delayLoad property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDelayLoad(Boolean value) {
        this.delayLoad = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Imported_Function" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Function_Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Virtual_Address" type="{http://www.w3.org/2001/XMLSchema}hexBinary" minOccurs="0"/>
     *                   &lt;element name="Hint" type="{http://www.w3.org/2001/XMLSchema}hexBinary" minOccurs="0"/>
     *                   &lt;element name="Ordinal" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "importedFunction"
    })
    public static class ImportedFunctions {

        @XmlElement(name = "Imported_Function", required = true)
        protected List<PEImportType.ImportedFunctions.ImportedFunction> importedFunction;

        /**
         * Gets the value of the importedFunction property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the importedFunction property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getImportedFunction().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link PEImportType.ImportedFunctions.ImportedFunction }
         * 
         * 
         */
        public List<PEImportType.ImportedFunctions.ImportedFunction> getImportedFunction() {
            if (importedFunction == null) {
                importedFunction = new ArrayList<PEImportType.ImportedFunctions.ImportedFunction>();
            }
            return this.importedFunction;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Function_Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Virtual_Address" type="{http://www.w3.org/2001/XMLSchema}hexBinary" minOccurs="0"/>
         *         &lt;element name="Hint" type="{http://www.w3.org/2001/XMLSchema}hexBinary" minOccurs="0"/>
         *         &lt;element name="Ordinal" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "functionName",
            "virtualAddress",
            "hint",
            "ordinal"
        })
        public static class ImportedFunction {

            @XmlElement(name = "Function_Name", required = true)
            protected String functionName;
            @XmlElement(name = "Virtual_Address", type = String.class)
            @XmlJavaTypeAdapter(HexBinaryAdapter.class)
            @XmlSchemaType(name = "hexBinary")
            protected byte[] virtualAddress;
            @XmlElement(name = "Hint", type = String.class)
            @XmlJavaTypeAdapter(HexBinaryAdapter.class)
            @XmlSchemaType(name = "hexBinary")
            protected byte[] hint;
            @XmlElement(name = "Ordinal")
            protected BigInteger ordinal;

            /**
             * Gets the value of the functionName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getFunctionName() {
                return functionName;
            }

            /**
             * Sets the value of the functionName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFunctionName(String value) {
                this.functionName = value;
            }

            /**
             * Gets the value of the virtualAddress property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public byte[] getVirtualAddress() {
                return virtualAddress;
            }

            /**
             * Sets the value of the virtualAddress property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setVirtualAddress(byte[] value) {
                this.virtualAddress = value;
            }

            /**
             * Gets the value of the hint property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public byte[] getHint() {
                return hint;
            }

            /**
             * Sets the value of the hint property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setHint(byte[] value) {
                this.hint = value;
            }

            /**
             * Gets the value of the ordinal property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getOrdinal() {
                return ordinal;
            }

            /**
             * Sets the value of the ordinal property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setOrdinal(BigInteger value) {
                this.ordinal = value;
            }

        }

    }

}
