//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.25 at 10:39:55 PM BST 
//


package org.mitre.maec.xmlschema.maec_core_1;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.HexBinaryAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * PESectionHeaderStruct is intended as container for the attributes present in a PE binary's section header structure.
 * 
 * <p>Java class for PESectionHeaderStruct complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PESectionHeaderStruct">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Hashes" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Hash" type="{http://maec.mitre.org/XMLSchema/maec-core-1}HashType" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Physical_Address" type="{http://www.w3.org/2001/XMLSchema}hexBinary" minOccurs="0"/>
 *         &lt;element name="Virtual_Address" type="{http://www.w3.org/2001/XMLSchema}hexBinary" minOccurs="0"/>
 *         &lt;element name="Size_Of_Raw_Data" type="{http://www.w3.org/2001/XMLSchema}hexBinary" minOccurs="0"/>
 *         &lt;element name="Pointer_To_Raw_Data" type="{http://www.w3.org/2001/XMLSchema}hexBinary" minOccurs="0"/>
 *         &lt;element name="Pointer_To_Relocations" type="{http://www.w3.org/2001/XMLSchema}hexBinary" minOccurs="0"/>
 *         &lt;element name="Pointer_To_Linenumbers" type="{http://www.w3.org/2001/XMLSchema}hexBinary" minOccurs="0"/>
 *         &lt;element name="Number_Of_Relocations" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="Number_Of_Linenumbers" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="Characteristics" type="{http://www.w3.org/2001/XMLSchema}hexBinary" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PESectionHeaderStruct", propOrder = {
    "hashes",
    "name",
    "physicalAddress",
    "virtualAddress",
    "sizeOfRawData",
    "pointerToRawData",
    "pointerToRelocations",
    "pointerToLinenumbers",
    "numberOfRelocations",
    "numberOfLinenumbers",
    "characteristics"
})
public class PESectionHeaderStruct {

    @XmlElement(name = "Hashes")
    protected PESectionHeaderStruct.Hashes hashes;
    @XmlElement(name = "Name")
    protected String name;
    @XmlElement(name = "Physical_Address", type = String.class)
    @XmlJavaTypeAdapter(HexBinaryAdapter.class)
    @XmlSchemaType(name = "hexBinary")
    protected byte[] physicalAddress;
    @XmlElement(name = "Virtual_Address", type = String.class)
    @XmlJavaTypeAdapter(HexBinaryAdapter.class)
    @XmlSchemaType(name = "hexBinary")
    protected byte[] virtualAddress;
    @XmlElement(name = "Size_Of_Raw_Data", type = String.class)
    @XmlJavaTypeAdapter(HexBinaryAdapter.class)
    @XmlSchemaType(name = "hexBinary")
    protected byte[] sizeOfRawData;
    @XmlElement(name = "Pointer_To_Raw_Data", type = String.class)
    @XmlJavaTypeAdapter(HexBinaryAdapter.class)
    @XmlSchemaType(name = "hexBinary")
    protected byte[] pointerToRawData;
    @XmlElement(name = "Pointer_To_Relocations", type = String.class)
    @XmlJavaTypeAdapter(HexBinaryAdapter.class)
    @XmlSchemaType(name = "hexBinary")
    protected byte[] pointerToRelocations;
    @XmlElement(name = "Pointer_To_Linenumbers", type = String.class)
    @XmlJavaTypeAdapter(HexBinaryAdapter.class)
    @XmlSchemaType(name = "hexBinary")
    protected byte[] pointerToLinenumbers;
    @XmlElement(name = "Number_Of_Relocations")
    protected BigInteger numberOfRelocations;
    @XmlElement(name = "Number_Of_Linenumbers")
    protected BigInteger numberOfLinenumbers;
    @XmlElement(name = "Characteristics", type = String.class)
    @XmlJavaTypeAdapter(HexBinaryAdapter.class)
    @XmlSchemaType(name = "hexBinary")
    protected byte[] characteristics;

    /**
     * Gets the value of the hashes property.
     * 
     * @return
     *     possible object is
     *     {@link PESectionHeaderStruct.Hashes }
     *     
     */
    public PESectionHeaderStruct.Hashes getHashes() {
        return hashes;
    }

    /**
     * Sets the value of the hashes property.
     * 
     * @param value
     *     allowed object is
     *     {@link PESectionHeaderStruct.Hashes }
     *     
     */
    public void setHashes(PESectionHeaderStruct.Hashes value) {
        this.hashes = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the physicalAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public byte[] getPhysicalAddress() {
        return physicalAddress;
    }

    /**
     * Sets the value of the physicalAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhysicalAddress(byte[] value) {
        this.physicalAddress = value;
    }

    /**
     * Gets the value of the virtualAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public byte[] getVirtualAddress() {
        return virtualAddress;
    }

    /**
     * Sets the value of the virtualAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVirtualAddress(byte[] value) {
        this.virtualAddress = value;
    }

    /**
     * Gets the value of the sizeOfRawData property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public byte[] getSizeOfRawData() {
        return sizeOfRawData;
    }

    /**
     * Sets the value of the sizeOfRawData property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSizeOfRawData(byte[] value) {
        this.sizeOfRawData = value;
    }

    /**
     * Gets the value of the pointerToRawData property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public byte[] getPointerToRawData() {
        return pointerToRawData;
    }

    /**
     * Sets the value of the pointerToRawData property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPointerToRawData(byte[] value) {
        this.pointerToRawData = value;
    }

    /**
     * Gets the value of the pointerToRelocations property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public byte[] getPointerToRelocations() {
        return pointerToRelocations;
    }

    /**
     * Sets the value of the pointerToRelocations property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPointerToRelocations(byte[] value) {
        this.pointerToRelocations = value;
    }

    /**
     * Gets the value of the pointerToLinenumbers property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public byte[] getPointerToLinenumbers() {
        return pointerToLinenumbers;
    }

    /**
     * Sets the value of the pointerToLinenumbers property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPointerToLinenumbers(byte[] value) {
        this.pointerToLinenumbers = value;
    }

    /**
     * Gets the value of the numberOfRelocations property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumberOfRelocations() {
        return numberOfRelocations;
    }

    /**
     * Sets the value of the numberOfRelocations property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumberOfRelocations(BigInteger value) {
        this.numberOfRelocations = value;
    }

    /**
     * Gets the value of the numberOfLinenumbers property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumberOfLinenumbers() {
        return numberOfLinenumbers;
    }

    /**
     * Sets the value of the numberOfLinenumbers property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumberOfLinenumbers(BigInteger value) {
        this.numberOfLinenumbers = value;
    }

    /**
     * Gets the value of the characteristics property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public byte[] getCharacteristics() {
        return characteristics;
    }

    /**
     * Sets the value of the characteristics property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCharacteristics(byte[] value) {
        this.characteristics = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Hash" type="{http://maec.mitre.org/XMLSchema/maec-core-1}HashType" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "hash"
    })
    public static class Hashes {

        @XmlElement(name = "Hash", required = true)
        protected List<HashType> hash;

        /**
         * Gets the value of the hash property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the hash property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getHash().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link HashType }
         * 
         * 
         */
        public List<HashType> getHash() {
            if (hash == null) {
                hash = new ArrayList<HashType>();
            }
            return this.hash;
        }

    }

}
