//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.25 at 10:39:55 PM BST 
//


package org.mitre.maec.xmlschema.maec_core_1;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ProcessorTypeEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ProcessorTypeEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="x86-32"/>
 *     &lt;enumeration value="x86-64"/>
 *     &lt;enumeration value="IA-64"/>
 *     &lt;enumeration value="PowerPC"/>
 *     &lt;enumeration value="ARM"/>
 *     &lt;enumeration value="Alpha"/>
 *     &lt;enumeration value="SPARC"/>
 *     &lt;enumeration value="z/Architecture"/>
 *     &lt;enumeration value="eSi-RISC"/>
 *     &lt;enumeration value="MIPS"/>
 *     &lt;enumeration value="Motorola 68k"/>
 *     &lt;enumeration value="Other"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ProcessorTypeEnum")
@XmlEnum
public enum ProcessorTypeEnum {

    @XmlEnumValue("x86-32")
    X_86_32("x86-32"),
    @XmlEnumValue("x86-64")
    X_86_64("x86-64"),
    @XmlEnumValue("IA-64")
    IA_64("IA-64"),
    @XmlEnumValue("PowerPC")
    POWER_PC("PowerPC"),
    ARM("ARM"),
    @XmlEnumValue("Alpha")
    ALPHA("Alpha"),
    SPARC("SPARC"),
    @XmlEnumValue("z/Architecture")
    Z_ARCHITECTURE("z/Architecture"),
    @XmlEnumValue("eSi-RISC")
    E_SI_RISC("eSi-RISC"),
    MIPS("MIPS"),
    @XmlEnumValue("Motorola 68k")
    MOTOROLA_68_K("Motorola 68k"),
    @XmlEnumValue("Other")
    OTHER("Other");
    private final String value;

    ProcessorTypeEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ProcessorTypeEnum fromValue(String v) {
        for (ProcessorTypeEnum c: ProcessorTypeEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
