//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.25 at 10:39:55 PM BST 
//


package org.mitre.maec.xmlschema.maec_core_1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for StructuredTextType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="StructuredTextType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice maxOccurs="unbounded">
 *           &lt;group ref="{http://maec.mitre.org/XMLSchema/maec-core-1}Structured_Text_Group"/>
 *           &lt;element ref="{http://maec.mitre.org/XMLSchema/maec-core-1}Block"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StructuredTextType", propOrder = {
    "textTitleOrTextOrCodeExampleLanguage"
})
public class StructuredTextType {

    @XmlElementRefs({
        @XmlElementRef(name = "Code_Example_Language", namespace = "http://maec.mitre.org/XMLSchema/maec-core-1", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Text_Title", namespace = "http://maec.mitre.org/XMLSchema/maec-core-1", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Block", namespace = "http://maec.mitre.org/XMLSchema/maec-core-1", type = Block.class, required = false),
        @XmlElementRef(name = "Images", namespace = "http://maec.mitre.org/XMLSchema/maec-core-1", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Text", namespace = "http://maec.mitre.org/XMLSchema/maec-core-1", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Code", namespace = "http://maec.mitre.org/XMLSchema/maec-core-1", type = JAXBElement.class, required = false)
    })
    protected List<Object> textTitleOrTextOrCodeExampleLanguage;

    /**
     * Gets the value of the textTitleOrTextOrCodeExampleLanguage property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the textTitleOrTextOrCodeExampleLanguage property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTextTitleOrTextOrCodeExampleLanguage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link Block }
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link Block.Images }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * 
     */
    public List<Object> getTextTitleOrTextOrCodeExampleLanguage() {
        if (textTitleOrTextOrCodeExampleLanguage == null) {
            textTitleOrTextOrCodeExampleLanguage = new ArrayList<Object>();
        }
        return this.textTitleOrTextOrCodeExampleLanguage;
    }

}
